import { useLocales } from 'src/locales';

// 메인 랜딩 5개국어 카피 (ko 기준, en/ja/cn/es 번역)
export const LANDING_STRINGS = {
  ko: {
    navAbout: '서비스 소개',
    navFrames: '프레임',
    navManual: '매뉴얼',
    navFaq: '자주 묻는 질문',
    ctaCreate: '무료 쇼핑몰 만들기',
    heroLine1: '쇼핑몰 제작비 없이',
    heroHi: '바로 판매를 시작',
    heroLine2: '하세요',
    heroSub1: '[[LOGO]]의 무료 쇼핑몰 서비스로',
    heroSub2: '사업자 누구나 가장 빠르고 간편하게 |나만의 쇼핑몰을 운영할 수 있습니다',
    heroBtn: '무료 쇼핑몰 만들기',
    heroAddrLabel: '내 쇼핑몰 주소 예시 —',
    heroAddrExample: '내쇼핑몰주소',
    searchTitle: '가맹점·상품 찾기',
    searchPlaceholder: '가맹점명 · 주소 · 상품명으로 검색',
    searchMin: '2글자 이상 입력해 주세요',
    searchNone: '검색 결과가 없습니다. 가맹점명 · 주소 · 상품명으로 검색해 보세요.',
    searchVisit: '방문하기',
    targetsTitle: '이런 분께 추천드립니다',
    targetsSub: '비용 부담 없이 시작하는 나만의 쇼핑몰! |국내는 물론 해외 고객까지 한 번에 판매하세요',
    t1Title: '쇼핑몰 제작 비용이 부담되는 사업자',
    t1Desc: '초기 비용 0원\n유지관리비 부담 없이 간편 운영',
    t2Title: '해외 고객에게 판매하고 싶은 사업자',
    t2Desc: '해외결제·글로벌결제 지원\n해외발행카드·위챗페이·알리페이 등',
    t3Title: 'SNS 중심으로 판매하는 사업자',
    t3Desc: 'SNS에서 상품을 소개하고\nShopGo에서 결제까지 완료',
    t4Title: '온라인 판매를 시작하려는 매장',
    t4Desc: '오프라인 매장을 온라인 매출로 연결\n지역 고객을 전국 고객으로 확대',
    langsTitle: '다국어 자동 번역',
    langsSub: '상품명과 상세 정보를 자동으로 번역하여, |해외 고객에게도 쉽게 판매할 수 있습니다',
    langKo: '한국어',
    langEn: '영어',
    langJa: '일본어',
    langCn: '중국어',
    langEs: '스페인어',
    actionsTitle: '지금 바로 시작하기',
    a1Title: '무료 쇼핑몰 프레임 선택',
    a1Desc: '6종 디자인 프레임을 미리 보고 선택하세요',
    a1Cta: '프레임 보기',
    a2Title: '온라인 쇼핑몰 신청서',
    a2Desc: '사업자 정보 입력 후 무료 쇼핑몰을 신청하세요',
    a2Cta: '신청하러 가기',
    a3Title: '관리자 매뉴얼',
    a3Desc: '쇼핑몰 운영을 위한 관리자 페이지 가이드',
    a3Cta: '매뉴얼 받기',
    footerShopInquiry: "쇼핑몰 문의",
    footerPayInquiry: "가맹 및 결제 문의",
    // 서비스 운영사 블록 — 법인명·주소 포함 전부 번역한다.
    // 법인명 표기는 아래 footerDisclaimer 안의 표기와 반드시 같아야 한다(같은 화면에 나란히 보인다).
    // 주소는 도로명주소 로마자 표기 기준. ja/cn 은 행정구역은 한자, 도로명은 음차.
    footerOperator: "서비스 운영사",
    footerPayName: "㈜포스페이",
    footerPayDesc: "국내 PG · 글로벌 통합결제 솔루션 제공",
    footerPayAddress: "서울시 성동구 연무장5가길 25 성수역SKV1타워 1702호",
    footerPlatformName: "㈜우진플랫폼",
    footerPlatformDesc: "무료 쇼핑몰 플랫폼 개발 및 운영",
    footerPlatformAddress: "서울시 영등포구 여의대방로 67길 11, 5층 에이5-41호(여의도동)",
    footerDisclaimer: "무료 쇼핑몰은 ㈜우진플랫폼이 제공하며, 결제서비스는 ㈜포스페이의 결제 솔루션을 통해 제공됩니다. 상품의 판매, 계약, 배송, 환불, 고객응대 및 쇼핑몰 운영에 관한 모든 책임은 해당 판매자에게 있으며, 양사는 플랫폼 및 결제서비스 제공자로서 거래의 당사자가 아닙니다.",
    policyTerms: "통합회원 이용약관",
    policyServiceAgreement: "무료쇼핑몰 서비스 이용동의",
    policyPrivacy: "개인정보처리방침",
    policyPayment: "PG 및 결제서비스 이용에 관한 정책",
    policyOperation: "무료서비스 운영정책",
    policyTermination: "서비스 해지 및 데이터 처리정책",
    policyResponsibility: "판매자 및 SHOPGO의 책임에 관한 정책",
    policyKoreanOnly: "본 약관·정책은 한국어 원문으로만 제공됩니다.",
    policyEffective: "시행일",
    policyOthers: "다른 약관·정책",
    policyNotFound: "문서를 찾을 수 없습니다",
    policyHome: "홈으로",
    agreeRequiredTag: "[필수]",
    agreeViewBtn: "보기",
    agreeNoticeTitle: "관련 정책 (가입 시 함께 적용됩니다 · 열람)",
    agreeAllError: "필수 약관에 모두 동의해 주세요.",
    trustHeading: "안전하게 운영되는 쇼핑몰",
    trustSub: "안전한 결제와 철저한 정보 보호로, 가맹점과 고객 모두가 안심할 수 있는 쇼핑 환경을 제공합니다",
    trust1Title: "안전결제",
    trust1Desc: "카드 등 결제정보는 PG(PSP)의\n결제 시스템을 통해 처리됩니다",
    trust2Title: "AWS 클라우드 인프라",
    trust2Desc: "검증된 글로벌 클라우드에서\n안정적으로 운영됩니다",
    trust3Title: "개인정보 암호화 저장",
    trust3Desc: "비밀번호·이름·연락처·주소 등을\n암호화하여 저장합니다",
    trust4Title: "결제정보 안전 관리",
    trust4Desc: "결제정보는 PG(PSP)사가 처리하며,\nSHOPGO는 전체 카드번호·비밀번호 등을 저장하지 않습니다",
  },
  en: {
    navAbout: 'About',
    navFrames: 'Frames',
    navManual: 'Manual',
    navFaq: 'FAQ',
    ctaCreate: 'Create your free store',
    heroLine1: 'No store-building costs —',
    heroHi: 'start selling right away',
    heroLine2: '',
    heroSub1: "With [[LOGO]]'s free online store service,",
    heroSub2: 'any business owner can run their own store |in the fastest, easiest way possible',
    heroBtn: 'Create your free store',
    heroAddrLabel: 'Example of my store address —',
    heroAddrExample: 'your-store',
    searchTitle: 'Find stores & products',
    searchPlaceholder: 'Search by store name, address, or product',
    searchMin: 'Please enter at least 2 characters',
    searchNone: 'No results found. Try searching by store name, address, or product.',
    searchVisit: 'Visit',
    targetsTitle: 'Perfect for businesses like yours',
    targetsSub: 'Launch your own store with no cost burden—|and sell to customers |at home and abroad, all at once',
    t1Title: 'Businesses worried about store-building costs',
    t1Desc: 'Zero upfront cost—\nrun it easily with no maintenance fees',
    t2Title: 'Businesses that want to sell to overseas customers',
    t2Desc: 'Overseas & global payments supported—\nforeign cards, WeChat Pay, Alipay, and more',
    t3Title: 'Businesses selling mainly through social media',
    t3Desc: 'Showcase products on social media\nand complete checkout on ShopGo',
    t4Title: 'Offline stores starting to sell online',
    t4Desc: 'Turn your offline store into online sales,\nexpanding from local to nationwide customers',
    langsTitle: 'Automatic multilingual translation',
    langsSub: 'Product names and details |are translated automatically, |so you can sell to overseas |customers with ease',
    langKo: 'Korean',
    langEn: 'English',
    langJa: 'Japanese',
    langCn: 'Chinese',
    langEs: 'Spanish',
    actionsTitle: 'Get started right now',
    a1Title: 'Choose your free store frame',
    a1Desc: 'Preview and pick from 6 design frames',
    a1Cta: 'View frames',
    a2Title: 'Online store application',
    a2Desc: 'Enter your business details and apply for your free store',
    a2Cta: 'Apply now',
    a3Title: 'Admin manual',
    a3Desc: 'A guide to the admin page for running your store',
    a3Cta: 'Get the manual',
    footerShopInquiry: "Store inquiries",
    footerPayInquiry: "Partnership & payment inquiries",
    footerOperator: "Operated by",
    footerPayName: "Forspay Co., Ltd.",
    footerPayDesc: "Domestic PG · Global integrated payment solutions",
    footerPayAddress: "Room 1702, Seongsu Station SK V1 Tower, 25 Yeonmujang 5ga-gil, Seongdong-gu, Seoul, Republic of Korea",
    footerPlatformName: "Woojin Platform Co., Ltd.",
    footerPlatformDesc: "Develops and operates the free online store platform",
    footerPlatformAddress: "5F, Room A5-41, 11 Yeouidaebang-ro 67-gil, Yeongdeungpo-gu, Seoul, Republic of Korea (Yeouido-dong)",
    footerDisclaimer: "The free store service is provided by Woojin Platform Co., Ltd., and payment services are provided through the payment solution of Forspay Co., Ltd. All responsibility for product sales, contracts, delivery, refunds, customer support and store operation rests with the respective seller; both companies act as the platform and payment service providers and are not parties to the transaction.",
    policyTerms: "Integrated Member Terms of Service",
    policyServiceAgreement: "Free Store Service Agreement",
    policyPrivacy: "Privacy Policy",
    policyPayment: "PG & Payment Service Policy",
    policyOperation: "Free Service Operating Policy",
    policyTermination: "Termination & Data Handling Policy",
    policyResponsibility: "Seller & SHOPGO Responsibility Policy",
    policyKoreanOnly: "These terms and policies are provided in the original Korean text only.",
    policyEffective: "Effective date",
    policyOthers: "Other terms & policies",
    policyNotFound: "Document not found",
    policyHome: "Go home",
    agreeRequiredTag: "[Required]",
    agreeViewBtn: "View",
    agreeNoticeTitle: "Related policies (also apply on sign-up · for reference)",
    agreeAllError: "Please agree to all required terms.",
    trustHeading: "A store you can run safely",
    trustSub: "With secure payments and thorough data protection, we provide a shopping environment both merchants and customers can trust.",
    trust1Title: "Secure payments",
    trust1Desc: "Card and other payment details are processed\nthrough the PG (PSP) payment system",
    trust2Title: "AWS cloud infrastructure",
    trust2Desc: "Runs reliably on a proven\nglobal cloud platform",
    trust3Title: "Encrypted personal data",
    trust3Desc: "Personal data (password, name, contact, address, etc.)\nis stored encrypted",
    trust4Title: "Payment data security",
    trust4Desc: "Payment information is handled by the PG (PSP) provider;\nSHOPGO does not store full card numbers, card passwords, or similar details",
  },
  ja: {
    navAbout: 'サービス紹介',
    navFrames: 'フレーム',
    navManual: 'マニュアル',
    navFaq: 'よくある質問',
    ctaCreate: '無料ショップを作成',
    heroLine1: 'ショップ制作費0円で、',
    heroHi: '今すぐ販売をスタート',
    heroLine2: 'しましょう',
    heroSub1: '[[LOGO]]の無料ショップサービスなら、',
    heroSub2: 'どんな事業者でも、もっとも速くかんたんに|自分だけのショップを運営できます',
    heroBtn: '無料ショップを作成',
    heroAddrLabel: 'あなたのショップアドレス例 —',
    heroAddrExample: 'あなたの店名',
    searchTitle: '加盟店・商品を探す',
    searchPlaceholder: '加盟店名・住所・商品名で検索',
    searchMin: '2文字以上で入力してください',
    searchNone: '検索結果がありません。加盟店名・住所・商品名で検索してみてください。',
    searchVisit: '訪問する',
    targetsTitle: 'こんな方におすすめです',
    targetsSub: '費用の負担なく始める自分だけのショップ！|国内はもちろん、|海外のお客様までまとめて販売しましょう',
    t1Title: 'ショップ制作費が負担に感じる事業者',
    t1Desc: '初期費用0円、\n維持管理費の負担なくかんたん運営',
    t2Title: '海外のお客様に販売したい事業者',
    t2Desc: '海外決済・グローバル決済に対応、\n海外発行カード・WeChat Pay・Alipayなど',
    t3Title: 'SNSを中心に販売する事業者',
    t3Desc: 'SNSで商品を紹介し、\nShopGoで決済まで完了',
    t4Title: 'オフライン店舗のオンライン販売を始めたい事業者',
    t4Desc: 'オフライン店舗をオンライン売上につなげ、\n地域のお客様を全国のお客様へ拡大',
    langsTitle: '多言語自動翻訳',
    langsSub: '商品名や詳細情報を自動で翻訳し、|海外のお客様にもかんたんに販売できます',
    langKo: '韓国語',
    langEn: '英語',
    langJa: '日本語',
    langCn: '中国語',
    langEs: 'スペイン語',
    actionsTitle: '今すぐ始める',
    a1Title: '無料ショップフレームを選択',
    a1Desc: '6種類のデザインフレームをプレビューして選べます',
    a1Cta: 'フレームを見る',
    a2Title: 'オンラインショップ申込書',
    a2Desc: '事業者情報を入力して、無料ショップをお申し込みください',
    a2Cta: '申し込みへ進む',
    a3Title: '管理者マニュアル',
    a3Desc: 'ショップ運営のための管理者ページガイド',
    a3Cta: 'マニュアルを入手',
    footerShopInquiry: "ショップに関するお問い合わせ",
    footerPayInquiry: "加盟・決済に関するお問い合わせ",
    footerOperator: "サービス運営会社",
    footerPayName: "㈱フォスペイ",
    footerPayDesc: "国内PG · グローバル統合決済ソリューション提供",
    footerPayAddress: "ソウル市城東区練武場5ガキル25 聖水駅SK V1タワー1702号",
    footerPlatformName: "㈱ウジンプラットフォーム",
    footerPlatformDesc: "無料ショップ プラットフォームの開発・運営",
    footerPlatformAddress: "ソウル市永登浦区汝矣大方路67ギル11、5階A5-41号（汝矣島洞）",
    footerDisclaimer: "無料ショップは㈱ウジンプラットフォームが提供し、決済サービスは㈱フォスペイの決済ソリューションを通じて提供されます。商品の販売、契約、配送、返金、顧客対応およびショップ運営に関するすべての責任は当該販売者にあり、両社はプラットフォームおよび決済サービスの提供者であって取引の当事者ではありません。",
    policyTerms: "統合会員利用規約",
    policyServiceAgreement: "無料ショップサービス利用同意",
    policyPrivacy: "個人情報処理方針",
    policyPayment: "PG・決済サービス利用ポリシー",
    policyOperation: "無料サービス運営ポリシー",
    policyTermination: "サービス解約およびデータ処理ポリシー",
    policyResponsibility: "販売者およびSHOPGOの責任に関するポリシー",
    policyKoreanOnly: "本規約・ポリシーは韓国語の原文のみで提供されます。",
    policyEffective: "施行日",
    policyOthers: "その他の規約・ポリシー",
    policyNotFound: "文書が見つかりません",
    policyHome: "ホームへ",
    agreeRequiredTag: "[必須]",
    agreeViewBtn: "見る",
    agreeNoticeTitle: "関連ポリシー（登録時に併せて適用されます・閲覧）",
    agreeAllError: "必須の規約にすべて同意してください。",
    trustHeading: "安心して運営できるショップ",
    trustSub: "安全な決済と徹底した情報保護により、加盟店とお客様の双方が安心できるショッピング環境を提供します",
    trust1Title: "安全な決済",
    trust1Desc: "カードなどの決済情報はPG（PSP）の\n決済システムを通じて処理されます",
    trust2Title: "AWSクラウドインフラ",
    trust2Desc: "実績あるグローバルクラウド上で\n安定して運営されます",
    trust3Title: "個人情報の暗号化保存",
    trust3Desc: "個人情報（パスワード・氏名・連絡先・住所など）は\n暗号化して保存します",
    trust4Title: "決済情報の安全管理",
    trust4Desc: "決済情報はPG（PSP）会社が処理し、\nSHOPGOはカード番号全体・暗証番号などを保存しません",
  },
  cn: {
    navAbout: '服务介绍',
    navFrames: '模板',
    navManual: '使用手册',
    navFaq: '常见问题',
    ctaCreate: '免费创建网店',
    heroLine1: '无需网店搭建费用，',
    heroHi: '立即开启销售',
    heroLine2: '',
    heroSub1: '借助 [[LOGO]] 的免费网店服务，',
    heroSub2: '每一位商家都能以最快、最简便的方式|运营专属于自己的网店',
    heroBtn: '免费创建网店',
    heroAddrLabel: '我的网店网址示例 —',
    heroAddrExample: '您的店铺名',
    searchTitle: '查找商户 · 商品',
    searchPlaceholder: '按商户名 · 地址 · 商品名搜索',
    searchMin: '请输入两个字以上',
    searchNone: '没有搜索结果。请尝试按商户名 · 地址 · 商品名搜索。',
    searchVisit: '前往访问',
    targetsTitle: '推荐给这样的您',
    targetsSub: '零负担开启专属于你的网店！|国内乃至海外客户，一次搞定销售',
    t1Title: '在意网店搭建成本的商家',
    t1Desc: '零初始成本，\n无维护费负担，轻松运营',
    t2Title: '希望向海外客户销售的商家',
    t2Desc: '支持海外支付、全球支付，\n境外发行卡、微信支付、支付宝等',
    t3Title: '以社交媒体为主销售的商家',
    t3Desc: '在社交媒体展示商品，\n在 ShopGo 完成支付',
    t4Title: '想开启线上销售的线下门店',
    t4Desc: '将线下门店连接到线上销售，\n把本地客户拓展为全国客户',
    langsTitle: '多语言自动翻译',
    langsSub: '自动翻译商品名称与详细信息，|让您轻松向海外客户销售',
    langKo: '韩语',
    langEn: '英语',
    langJa: '日语',
    langCn: '中文',
    langEs: '西班牙语',
    actionsTitle: '立即开始',
    a1Title: '选择免费网店模板',
    a1Desc: '预览并挑选 6 款设计模板',
    a1Cta: '查看模板',
    a2Title: '线上网店申请表',
    a2Desc: '填写商家信息后即可申请免费网店',
    a2Cta: '前往申请',
    a3Title: '管理员手册',
    a3Desc: '网店运营所需的管理后台指南',
    a3Cta: '获取手册',
    footerShopInquiry: "商城咨询",
    footerPayInquiry: "加盟及支付咨询",
    footerOperator: "服务运营方",
    footerPayName: "㈱Forspay",
    footerPayDesc: "国内PG · 全球综合支付解决方案",
    footerPayAddress: "首尔市城东区练武场5街25号 圣水站SK V1大厦1702室",
    footerPlatformName: "㈱友进平台",
    footerPlatformDesc: "免费商城平台的开发与运营",
    footerPlatformAddress: "首尔市永登浦区汝矣大方路67街11号 5层A5-41室（汝矣岛洞）",
    footerDisclaimer: "免费商城由㈱友进平台提供，支付服务通过㈱Forspay的支付解决方案提供。商品销售、合同、配送、退款、客户服务及商城运营的全部责任由相应卖家承担，两家公司作为平台及支付服务提供方，并非交易当事人。",
    policyTerms: "综合会员服务条款",
    policyServiceAgreement: "免费商城服务使用同意",
    policyPrivacy: "隐私政策",
    policyPayment: "PG及支付服务使用政策",
    policyOperation: "免费服务运营政策",
    policyTermination: "服务解约及数据处理政策",
    policyResponsibility: "卖家及SHOPGO责任政策",
    policyKoreanOnly: "本条款与政策仅提供韩语原文。",
    policyEffective: "施行日期",
    policyOthers: "其他条款与政策",
    policyNotFound: "未找到该文档",
    policyHome: "返回首页",
    agreeRequiredTag: "[必填]",
    agreeViewBtn: "查看",
    agreeNoticeTitle: "相关政策（注册时一并适用·仅供查阅）",
    agreeAllError: "请同意全部必需条款。",
    trustHeading: "可安心运营的商城",
    trustSub: "以安全的支付与彻底的信息保护，为商家与顾客打造双方都安心的购物环境",
    trust1Title: "安全支付",
    trust1Desc: "银行卡等支付信息通过PG（PSP）的\n支付系统进行处理",
    trust2Title: "AWS云基础设施",
    trust2Desc: "在成熟的全球云平台上\n稳定运行",
    trust3Title: "个人信息加密存储",
    trust3Desc: "个人信息（密码·姓名·联系方式·地址等）\n均加密存储",
    trust4Title: "支付信息安全管理",
    trust4Desc: "支付信息由PG（PSP）公司处理，\nSHOPGO不存储完整卡号·密码等信息",
  },
  es: {
    navAbout: 'Servicio',
    navFrames: 'Plantillas',
    navManual: 'Manual',
    navFaq: 'Preguntas frecuentes',
    ctaCreate: 'Crea tu tienda gratis',
    heroLine1: 'Sin costes de creación,',
    heroHi: 'empieza a vender',
    heroLine2: ' hoy mismo',
    heroSub1: 'Con el servicio de tienda online gratuita de [[LOGO]],',
    heroSub2: 'cualquier negocio puede gestionar |su propia tienda |de la forma más rápida y sencilla',
    heroBtn: 'Crea tu tienda gratis',
    heroAddrLabel: 'Ejemplo de la dirección de mi tienda —',
    heroAddrExample: 'tu-tienda',
    searchTitle: 'Buscar comercios y productos',
    searchPlaceholder: 'Busca por comercio, dirección o producto',
    searchMin: 'Introduce al menos 2 caracteres',
    searchNone: 'No se encontraron resultados. Prueba a buscar por comercio, dirección o producto.',
    searchVisit: 'Visitar',
    targetsTitle: 'Recomendado para ti si eres así',
    targetsSub: '¡Tu propia tienda sin cargas de coste! |Vende de una sola vez a clientes |nacionales y también del extranjero',
    t1Title: 'Un negocio al que le pesan los costes de crear la tienda',
    t1Desc: 'Coste inicial de 0,\ngestión sencilla sin gastos de mantenimiento',
    t2Title: 'Un negocio que quiere vender a clientes del extranjero',
    t2Desc: 'Pagos internacionales y globales,\ntarjetas extranjeras, WeChat Pay, Alipay y más',
    t3Title: 'Un negocio que vende a través de redes sociales',
    t3Desc: 'Muestra tus productos en redes sociales\ny completa el pago en ShopGo',
    t4Title: 'Una tienda física que empieza a vender online',
    t4Desc: 'Conecta tu tienda física con las ventas online\ny amplía de clientes locales a todo el país',
    langsTitle: 'Traducción automática multilingüe',
    langsSub: 'Traduce automáticamente |los nombres y detalles de tus productos |para vender con facilidad |también a clientes del extranjero',
    langKo: 'Coreano',
    langEn: 'Inglés',
    langJa: 'Japonés',
    langCn: 'Chino',
    langEs: 'Español',
    actionsTitle: 'Empieza ahora mismo',
    a1Title: 'Elige tu plantilla de tienda gratis',
    a1Desc: 'Previsualiza y elige entre 6 plantillas de diseño',
    a1Cta: 'Ver plantillas',
    a2Title: 'Solicitud de tienda online',
    a2Desc: 'Introduce los datos de tu negocio y solicita tu tienda gratis',
    a2Cta: 'Ir a la solicitud',
    a3Title: 'Manual del administrador',
    a3Desc: 'Guía del panel de administración para gestionar tu tienda',
    a3Cta: 'Obtener el manual',
    footerShopInquiry: "Consultas sobre la tienda",
    footerPayInquiry: "Consultas de afiliación y pagos",
    footerOperator: "Operado por",
    footerPayName: "Forspay Co., Ltd.",
    footerPayDesc: "PG nacional · Soluciones globales de pago integrado",
    footerPayAddress: "Oficina 1702, Seongsu Station SK V1 Tower, 25 Yeonmujang 5ga-gil, Seongdong-gu, Seúl, República de Corea",
    footerPlatformName: "Woojin Platform Co., Ltd.",
    footerPlatformDesc: "Desarrollo y operación de la plataforma de tiendas gratuitas",
    footerPlatformAddress: "5.ª planta, oficina A5-41, 11 Yeouidaebang-ro 67-gil, Yeongdeungpo-gu, Seúl, República de Corea (Yeouido-dong)",
    footerDisclaimer: "La tienda gratuita es proporcionada por Woojin Platform Co., Ltd. y los servicios de pago se prestan mediante la solución de pago de Forspay Co., Ltd. Toda la responsabilidad sobre la venta de productos, contratos, envíos, reembolsos, atención al cliente y explotación de la tienda corresponde al vendedor correspondiente; ambas empresas actúan como proveedoras de la plataforma y del servicio de pago y no son parte de la transacción.",
    policyTerms: "Términos de servicio para miembros",
    policyServiceAgreement: "Acuerdo de servicio de tienda gratuita",
    policyPrivacy: "Política de privacidad",
    policyPayment: "Política de servicios de pago y PG",
    policyOperation: "Política de operación del servicio gratuito",
    policyTermination: "Política de cancelación y tratamiento de datos",
    policyResponsibility: "Política de responsabilidad del vendedor y SHOPGO",
    policyKoreanOnly: "Estos términos y políticas se ofrecen únicamente en su texto original en coreano.",
    policyEffective: "Fecha de entrada en vigor",
    policyOthers: "Otros términos y políticas",
    policyNotFound: "Documento no encontrado",
    policyHome: "Ir al inicio",
    agreeRequiredTag: "[Obligatorio]",
    agreeViewBtn: "Ver",
    agreeNoticeTitle: "Políticas relacionadas (se aplican al registrarse · consulta)",
    agreeAllError: "Debe aceptar todos los términos obligatorios.",
    trustHeading: "Una tienda que puede operar con tranquilidad",
    trustSub: "Con pagos seguros y una protección de datos rigurosa, ofrecemos un entorno de compra en el que comerciantes y clientes pueden confiar",
    trust1Title: "Pagos seguros",
    trust1Desc: "Los datos de pago (tarjeta, etc.) se procesan\na través del sistema de pago PG (PSP)",
    trust2Title: "Infraestructura en la nube de AWS",
    trust2Desc: "Funciona de forma estable sobre una\nnube global contrastada",
    trust3Title: "Datos personales cifrados",
    trust3Desc: "Los datos personales (contraseña, nombre, contacto, dirección, etc.)\nse almacenan cifrados",
    trust4Title: "Gestión segura de los datos de pago",
    trust4Desc: "Los datos de pago los gestiona el proveedor PG (PSP);\nSHOPGO no almacena el número completo de la tarjeta, la contraseña ni datos similares",
  },
};

// 현재 선택 언어의 랜딩 문자열 반환 (없으면 한국어)
export function useLandingT() {
  const { currentLang } = useLocales();
  const lang = currentLang?.value || 'ko';
  return LANDING_STRINGS[lang] || LANDING_STRINGS.ko;
}

// ----------------------------------------------------------------------
// 서브 페이지(frames / apply / manual) + 프레임 카탈로그 번역 (flat dotted keys)
// 접근: useSubpageT() → st('apply.sec1'), useFrameT() → ft(frameKey) → {title,keyword,desc,recommend}
// ----------------------------------------------------------------------
const SUBPAGE_FLAT = {
  ko: {
    "frames.title": "무료 쇼핑몰 프레임",
    "frames.desc1": "브랜드와 업종에 맞는 다양한 |쇼핑몰 프레임을 선택해 보세요",
    "frames.desc2": "미리보기를 통해 실제 디자인과 화면 구성을 |확인하실 수 있습니다",
    "frames.noticeContent": "미리보기의 상품·카테고리·배너는 예시이며, 개설 후 직접 설정하실 수 있습니다",
    'frames.recommendLabel': '추천 업종',
    'frames.preview': '미리보기',
    'frames.comingSoon': '준비중',
    'frames.applyBtn': '이 프레임으로 신청',
    'frames.ctaLine1': '마음에 드는 프레임을 선택하셨다면',
    'frames.ctaLine2': '이제 신청만으로 |모든 준비가 완료됩니다',
    "frames.groupNote": "프레임별 홈·상품 화면 디자인은 다르며, 주문·결제 등 주요 기능 화면은 동일하게 제공됩니다",
    // .short 는 카드 우측 상단 배지용 — 카드 폭이 좁아 '· 프레임1·2' 꼬리표가 붙은
    //  .title 을 그대로 넣으면 말줄임표로 잘린다. .desc 는 그 배지의 마우스오버 설명.
    "frames.group.shop.title": "쇼핑몰형 · 프레임1·2",
    "frames.group.shop.short": "쇼핑몰형",
    "frames.group.shop.desc": "상단 카테고리 메뉴와 상품 목록 화면을 갖춘 구성입니다. 카테고리와 상품 수가 많은 몰에 적합합니다.",
    "frames.group.column.title": "블로그형 · 프레임3·4",
    "frames.group.column.short": "블로그형",
    "frames.group.column.desc": "모바일에 맞춘 좁은 한 컬럼 구성입니다. 홈과 상품 화면의 분위기가 프레임마다 다릅니다.",
    "frames.group.landing.title": "단일·소수 상품 랜딩형 · 프레임5·6",
    "frames.group.landing.short": "단일·소수 상품형",
    "frames.group.landing.desc": "대표 상품 한두 개를 크게 보여주는 랜딩 구성입니다. 두 프레임은 홈과 상품 화면의 디자인·색감이 다르고, 장바구니·주문·마이페이지 화면은 동일합니다.",
    'apply.title': '온라인 쇼핑몰 신청서',
    'apply.desc': '입력하신 내용을 확인 후 담당자가 연락드립니다. 모든 필수 항목 입력 후 약정서에 동의해 주세요.',
    'apply.sec1': '01 · 사업자 정보',
    'apply.sec2': '02 · 대표자 정보',
    'apply.sec3': '03 · 담당자 정보',
    'apply.sec4': '04 · 운영 정보',
    'apply.sec5': '05 · 쇼핑몰 주소 (가맹점명)',
    'apply.sec6': '06 · 프레임 선택',
    'apply.sec7': '07 · 약정서',
    'apply.fBizName': '사업자명',
    'apply.fBizNo': '사업자번호',
    'apply.fMailOrder': '통신판매업신고번호',
    'apply.fCeoName': '대표자명',
    'apply.fCeoPhone': '대표자 연락처',
    'apply.fCeoEmail': '대표자 이메일',
    'apply.fMgrName': '담당자명',
    'apply.fMgrPhone': '담당자 연락처',
    'apply.fMgrEmail': '담당자 이메일',
    'apply.fCsPhone': '고객센터 번호',
    'apply.fReferrer': '영업추천인',
    'apply.fSlug': '사용하실 가맹점명',
    'apply.fFrame': '원하시는 디자인 프레임',
    'apply.phBizNo': '10자리 숫자',
    'apply.phMailOrder': '예: 2024-서울강남-1234',
    'apply.phCsPhone': '1588-0000 등',
    'apply.phReferrer': '추천인이 있으면 입력해 주세요',
    'apply.phSlug': '영문 소문자/숫자/하이픈',
    'apply.framePlaceholder': '프레임 선택',
    'apply.slugExampleWord': '가맹점명',
    'apply.exampleLabel': '예시',
    'apply.frameHintPre': '프레임을 자세히 보려면 ',
    'apply.frameHintLink': '프레임 페이지',
    'apply.frameHintPost': '를 열어 미리보기 후 선택하세요',
    'apply.cancel': '취소',
    'apply.submit': '신청서 제출',
    'apply.submitting': '접수 중…',
    'apply.alertWarn': '입력값을 확인해 주세요. 누락되거나 형식이 맞지 않는 항목이 있습니다.',
    'apply.agreeLabel': '위 무료 쇼핑몰 제공 약정서 내용을 확인하였으며, 이에 동의합니다. (필수)',
    'apply.agreeError': '약정서 동의가 필요합니다',
    'apply.vBizName': '사업자명을 입력해 주세요',
    'apply.vBizNo': '사업자번호 10자리를 입력해 주세요',
    'apply.vCeoName': '대표자명을 입력해 주세요',
    'apply.vCeoPhone': '대표자 연락처를 확인해 주세요',
    'apply.vEmail': '이메일 형식을 확인해 주세요',
    'apply.vMgrName': '담당자명을 입력해 주세요',
    'apply.vMgrPhone': '담당자 연락처를 확인해 주세요',
    'apply.vSlug': '영문 소문자/숫자/하이픈 3~30자 (시작·끝은 영숫자)',
    'apply.vFrame': '프레임을 1개 선택해 주세요',
    'apply.vAgreed': '약정서 동의가 필요합니다',
    'apply.tCheckInput': '입력값을 확인해 주세요',
    'apply.tSuccess': '신청이 접수되었습니다',
    'apply.tDupSlug': '이미 사용 중인 URL명입니다',
    'apply.tError': '접수 중 오류가 발생했습니다',
    'apply.tServerError': '서버 오류로 접수에 실패했습니다',
    'manual.title': '관리자 페이지 가이드',
    "faq.title": "자주 묻는 질문",
    "faq.desc": "가맹점 운영에 자주 나오는 질문을 결제·정산과 쇼핑몰 운영으로 나눠 정리했습니다.",
    "faq.catPay": "결제 · PG · 정산",
    "faq.catShop": "쇼핑몰 운영",
    "faq.notFound": "원하는 답변을 찾지 못하셨나요?",
    "faq.askShop": "쇼핑몰 기능 문의",
    "faq.askPay": "가맹·결제 문의",
    "faq.p1.q": "SHOPGO에서 온라인 결제는 어떻게 이루어지나요?",
    "faq.p1.a": "SHOPGO는 PG(Payment Gateway)와 연동되어 안전하게 결제가 진행됩니다. 고객은 다양한 결제수단으로 주문할 수 있으며, 결제가 완료되면 주문 정보가 판매자에게 자동으로 전달됩니다.",
    "faq.p2.q": "SHOPGO는 어떤 PG(결제대행사)를 지원하나요?",
    "faq.p2.a": "서비스 오픈 시점에는 페이레터(PayLetter)와 나이스정보통신(NICE)이 지원되며, NHN KCP·한국정보통신(KICC)·KSNET 및 기타 국내·글로벌 PG가 순차적으로 지원될 예정입니다. SHOPGO는 지속적으로 다양한 PG사를 확대하여 판매자가 원하는 결제환경을 선택할 수 있도록 지원합니다.",
    "faq.p3.q": "사용할 수 있는 결제수단은 무엇인가요?",
    "faq.p3.a": "선택한 PG사에 따라 신용카드·체크카드, 계좌이체, 간편결제(카카오페이·네이버페이·삼성페이), 해외발행카드(비자카드·마스터카드·JCB·UPI(은련카드)·AMX(아멕스카드)), 해외간편결제(위챗페이·알리페이·라인페이)를 이용할 수 있습니다. 제공되는 결제수단은 PG사별로 일부 차이가 있을 수 있습니다.",
    "faq.p4.q": "PG 계약은 반드시 해야 하나요?",
    "faq.p4.a": "네. 온라인(모바일) 결제를 이용하려면 PG 계약이 필요합니다. SHOPGO에서는 PG 신청부터 심사, 계약, 쇼핑몰 연동까지 전 과정을 지원해 드립니다.",
    "faq.p5.q": "PG 심사는 얼마나 걸리나요?",
    "faq.p5.a": "일반적으로 영업일 기준 2~3주 정도 소요되며, 업종 및 제출 서류에 따라 기간이 달라질 수 있습니다.",
    "faq.p6.q": "결제 수수료는 얼마인가요?",
    "faq.p6.a": "결제 수수료는 선택한 PG사와 업종에 따라 달라집니다. 정확한 수수료는 PG 심사 완료 후 안내해 드립니다.",
    "faq.p7.q": "정산은 어떻게 이루어지나요?",
    "faq.p7.a": "고객이 결제를 완료하면 계약한 PG사의 정산 정책에 따라 판매자에게 정산됩니다. 정산주기와 지급일은 PG사별 정책에 따라 운영됩니다.",
    "faq.p8.q": "해외 고객도 결제가 가능한가요?",
    "faq.p8.a": "가능합니다. 지원되는 PG를 선택하면 해외발행카드(비자카드·마스터카드·JCB·UPI(은련카드)·AMX(아멕스카드)) 및 해외간편결제(위챗페이·알리페이·라인페이)를 이용할 수 있습니다.",
    "faq.p9.q": "PG를 변경하거나 추가할 수 있나요?",
    "faq.p9.a": "가능합니다. 사업 규모와 운영환경에 맞게 다른 PG를 추가하거나 변경할 수 있으며, SHOPGO에서 연동을 지원합니다.",
    "faq.p10.q": "결제나 정산에 문제가 발생하면 어디로 문의하나요?",
    "faq.p10.a": "결제 승인, 취소, 정산, 수수료 등 결제 관련 문의는 SHOPGO 고객센터 또는 담당 영업담당자를 통해 접수해 주시면 신속하게 지원해 드립니다. (가맹·결제 문의: office@forspay.com)",
    "faq.p11.q": "무료쇼핑몰인데 결제서비스도 무료인가요?",
    "faq.p11.a": "SHOPGO 쇼핑몰 이용은 무료입니다. 다만, PG 결제서비스는 금융서비스이므로 계약한 PG사의 결제수수료 및 관련 비용은 별도로 적용됩니다.",
    "faq.p12.q": "PG사 결제내역은 어디서 확인하나요?",
    "faq.p12.a": "계약한 PG사에서 제공하는 결제내역(거래내역) 페이지에서 직접 확인·출력하실 수 있습니다. 이용 중인 PG사의 조회 페이지는 아래와 같습니다.",
    "faq.s1.q": "쇼핑몰 주소(도메인)는 어떻게 정해지나요?",
    "faq.s1.a": "신청 시 희망하신 이름으로 ‘가맹점명.shopgo.co.kr’ 형태의 주소가 자동 생성됩니다. 별도의 도메인 구매 없이 바로 쇼핑몰을 운영하실 수 있습니다.",
    "faq.s2.q": "관리자 계정은 어떻게 받나요?",
    "faq.s2.a": "승인(개설) 시 안내 메일로 관리자 페이지 주소·아이디·초기 비밀번호가 발송됩니다. 초기 비밀번호는 아이디와 동일하므로, 로그인 후 우측 상단 프로필 → 비밀번호 변경에서 반드시 변경해 주세요.",
    "faq.s3.q": "상품은 어떻게 등록하나요?",
    "faq.s3.a": "관리자 페이지 → 상품관리 → 상품 추가에서 상품명·판매가·대표이미지·옵션·재고를 입력해 등록합니다. 상품을 등록하려면 카테고리가 먼저 있어야 하니, 상품관리에서 카테고리를 만든 뒤 등록해 주세요.",
    "faq.s4.q": "상품을 잠시 숨기고 싶어요.",
    "faq.s4.a": "상품 목록에서 해당 상품 상태를 ‘비공개(숨김)’로 바꾸면 쇼핑몰에 노출되지 않습니다. 언제든 다시 ‘판매중’으로 되돌릴 수 있습니다.",
    "faq.s5.q": "할인가는 어떻게 표시하나요?",
    "faq.s5.a": "상품 등록/수정에서 ‘할인 표시하기’를 체크하면 ‘할인 전 가격(정가)’ 입력칸이 나타납니다. 정가를 판매가보다 높게 입력하면 쇼핑몰에 취소선과 할인율(%)이 함께 표시됩니다.",
    "faq.s6.q": "주문 확인과 송장 입력은 어떻게 하나요?",
    "faq.s6.a": "관리자 페이지 → 주문관리에서 들어온 주문을 확인하고 상태를 변경합니다. 상품 발송 후 택배사를 선택하고 송장번호를 입력해 저장하면, 구매자 주문내역에 택배사·송장번호와 ‘배송조회’ 링크가 표시됩니다.",
    "faq.s7.q": "배송비는 어떻게 설정하나요?",
    "faq.s7.a": "설정관리 → 배송비설정에서 기본 배송비와 무료배송 기준금액을 설정합니다. 기준금액 이상 주문 시 배송비가 무료로 적용되며, 배송비를 설정하지 않으면 무료배송으로 처리됩니다.",
    "faq.s8.q": "회원 관리는 어디서 하나요?",
    "faq.s8.a": "관리자 페이지 → 회원관리에서 가입 회원을 조회하고 상태 변경·비밀번호 변경 등을 처리할 수 있습니다. 회원 아이디·이름·전화번호로 검색하실 수 있습니다.",
    "faq.s9.q": "공지사항·문의 게시판이 있나요?",
    "faq.s9.a": "개설 시 공지사항과 1:1문의 게시판이 기본 제공됩니다. 1:1문의는 작성자 본인과 관리자만 볼 수 있으며, 문의 글에 답변을 작성해 저장하면 고객에게 답변이 등록됩니다.",
    "faq.s10.q": "운영 매뉴얼은 어디서 보나요?",
    "faq.s10.a": "개설 안내 메일의 매뉴얼 링크 또는 shopgo.co.kr 매뉴얼 페이지에서 관리자 가이드를 확인하실 수 있습니다. 처음 사용자를 위해 상품 등록부터 주문·배송 처리까지 순서대로 안내되어 있습니다.",
    'manual.preApply': '아직 신청 전이신가요?',
    'manual.applyLink': '무료 쇼핑몰 신청하기',
    'complete.title': '신청이 접수되었습니다',
    'complete.desc1': '담당자가 검토 후 |입력하신 연락처로 연락드리겠습니다',
    'complete.desc2': '승인이 완료되면 신청하신 가맹점명으로 |쇼핑몰이 개설됩니다',
    'complete.home': '홈으로',
    'complete.manual': '관리자 매뉴얼 받기',
    "frame.shop:1.title": "탐색 중심형",
    "frame.shop:1.keyword": "다카테고리",
    "frame.shop:1.desc": "많은 상품을 쉽고 빠르게 찾아볼 수 있는 쇼핑몰\n상단 카테고리 메뉴로 원하는 상품을 빠르게 탐색하고, 전체 폭 슬라이드 배너와 인기상품·품절임박 상품을 한눈에 확인할 수 있습니다",
    "frame.shop:1.recommend": "종합 쇼핑몰 (가전·잡화·식품 등)",
    "frame.shop:2.title": "비주얼 중심형",
    "frame.shop:2.keyword": "단일 브랜드",
    "frame.shop:2.desc": "브랜드의 이미지, 감성을 효과적으로 보여주는 쇼핑몰\n큰 메인 배너를 중심으로 브랜드와 시즌 분위기를 강조하고, 상단 메뉴를 간결하게 구성해 상품과 비주얼에 집중할 수 있습니다",
    "frame.shop:2.recommend": "화장품 · 패션 등 단일/소수 브랜드 매장",
    'frame.shop:4.title': '다카테고리 잡화몰',
    'frame.shop:4.keyword': '패션·잡화 다품목',
    'frame.shop:4.desc': '카테고리별 상품 그리드를 다채롭게 배치\n가방·시계·신발·액세서리 등 종류별 분류 진열',
    'frame.shop:4.recommend': '카테고리가 많고 SKU가 다양한 잡화몰 (가방·시계·신발·액세서리 등)',
    "frame.blog:1.title": "매거진형",
    "frame.blog:1.keyword": "디자이너 셀렉트샵",
    "frame.blog:1.desc": "상품과 브랜드 스토리를 감각적으로 보여주는 쇼핑몰\n‘Cover Story’와 ‘Editor’s Pick’ 구성으로 상품을 매거진처럼 소개하고, 큰 배너를 활용해 하나의 상품도 풍성하고 돋보이게 표현할 수 있습니다",
    "frame.blog:1.recommend": "패션, 주얼리, 액세서리, 디자이너 브랜드",
    "frame.blog:2.title": "스크롤형",
    "frame.blog:2.keyword": "한 컬럼 큐레이션",
    "frame.blog:2.desc": "상품을 자연스럽게 둘러보기 좋은 심플한 쇼핑몰\n카테고리별 상품을 한 컬럼에 차례로 보여주어, 모바일에서 스크롤하며 편하게 상품을 둘러볼 수 있습니다",
    "frame.blog:2.recommend": "상품 수가 많지 않은 큐레이션 · 셀렉트샵\n※ 상품 수가 많은 몰은 탐색 중심형을 추천합니다.",
    "frame.blog:4.title": "프리미엄 에디토리얼형",
    "frame.blog:4.keyword": "단일·소수 카테고리",
    "frame.blog:4.desc": "하나의 상품을 작품처럼 돋보이게 보여주는 쇼핑몰\n큰 비주얼과 매거진형 레이아웃을 활용해 상품의 가치와 디테일을 강조하고, 흑백 톤과 절제된 타이포그래피로 고급스럽고 세련된 분위기를 연출합니다",
    "frame.blog:4.recommend": "프리미엄 디자인 가구 · 한정 에디션 브랜드",
    'frame.blog:5.title': '다크 럭셔리',
    'frame.blog:5.keyword': '고급·한정판 브랜드',
    'frame.blog:5.desc': '다크 톤 배경으로 절제·고급·신비로운 무드\n브랜드 헤리티지를 담은 문구',
    'frame.blog:5.recommend': '럭셔리 침구·생활용품, 프리미엄 브랜드, 한정 컬렉션',
    'frame.blog:6.title': '신뢰형 단일 브랜드',
    'frame.blog:6.keyword': '소수 품목 · 신뢰형',
    'frame.blog:6.desc': '정돈된 깔끔한 레이아웃\n신뢰 포인트·통계·갤러리로 믿음을 단계적으로 전달',
    'frame.blog:6.recommend': '단일/소수 SKU 브랜드 (생수·영양제, 단일 화장품 라인, 일상 소비재 등)',
    'frame.blog:7.title': '동양 미니멀',
    'frame.blog:7.keyword': '차·한방·자연주의',
    'frame.blog:7.desc': '베이지 톤 + 한자 키워드\n차분한 카피, 일본·동양 미감',
    'frame.blog:7.recommend': '차/한방차, 전통식품, 자연주의 화장품, 수공예 라이프스타일',
    'frame.blog:8.title': '트렌디 그래픽',
    'frame.blog:8.keyword': 'MZ 타깃 신상',
    'frame.blog:8.desc': '비비드 컬러 + 모노크롬 블록 분할\n강한 카피, 트렌디·세련된 그래픽 무드',
    'frame.blog:8.recommend': 'MZ 타깃 신상품/한정판 (인디 뷰티, 스니커즈, 헬스케어, 트렌디 액세서리 등)',
    "frame.blog:9.title": "파스텔 감성형",
    "frame.blog:9.keyword": "단일·소수 카테고리",
    "frame.blog:9.desc": "부드럽고 따뜻한 분위기로 상품을 보여주는 쇼핑몰\n핑크·파스텔 톤과 폴라로이드 감성으로 상품과 후기를 자연스럽게 표현해, 친근하고 감각적인 분위기를 연출합니다",
    "frame.blog:9.recommend": "향수 · 화장품 · 액세서리 · 캔들 · 디퓨저",
  },
  en: {
    "frames.title": "Free Online Store Frames",
    "frames.desc1": "Choose from a range of store frames |that fit your brand and industry",
    "frames.desc2": "Use the preview to see |the actual design and layout",
    "frames.noticeContent": "Products, categories and banners in the preview are examples — you can set your own after opening",
    "frames.recommendLabel": "Recommended for",
    "frames.preview": "Preview",
    "frames.comingSoon": "Coming soon",
    "frames.applyBtn": "Apply with this frame",
    "frames.ctaLine1": "Once you've picked a frame you like,",
    "frames.ctaLine2": "just submit your application |and you're all set",
    "frames.groupNote": "The home and product screens differ by frame, while the order, payment and other core screens are the same",
    "frames.group.shop.title": "Storefront · Frames 1-2",
    "frames.group.shop.short": "Storefront",
    "frames.group.shop.desc": "A layout with a top category menu and a product list page. Best for stores with many categories and products.",
    "frames.group.column.title": "Blog style · Frames 3-4",
    "frames.group.column.short": "Blog style",
    "frames.group.column.desc": "A narrow single-column layout built for mobile. The mood of the home and product pages differs by frame.",
    "frames.group.landing.title": "Single/few product landing · Frames 5-6",
    "frames.group.landing.short": "Few-product landing",
    "frames.group.landing.desc": "A landing layout that features one or two products prominently. The two frames differ in the design and colour of the home and product pages; the cart, order and my-page screens are identical.",
    "apply.title": "Online Store Application",
    "apply.desc": "Our team will contact you after reviewing your submission. Please fill in all required fields and agree to the agreement.",
    "apply.sec1": "01 · Business Info",
    "apply.sec2": "02 · Representative Info",
    "apply.sec3": "03 · Contact Person Info",
    "apply.sec4": "04 · Operations Info",
    "apply.sec5": "05 · Store Address (store name)",
    "apply.sec6": "06 · Frame Selection",
    "apply.sec7": "07 · Agreement",
    "apply.fBizName": "Business name",
    "apply.fBizNo": "Business registration no.",
    "apply.fMailOrder": "Mail-order business report no.",
    "apply.fCeoName": "Representative name",
    "apply.fCeoPhone": "Representative phone",
    "apply.fCeoEmail": "Representative email",
    "apply.fMgrName": "Contact person name",
    "apply.fMgrPhone": "Contact person phone",
    "apply.fMgrEmail": "Contact person email",
    "apply.fCsPhone": "Customer service number",
    "apply.fReferrer": "Sales referrer",
    "apply.fSlug": "Store name to use",
    "apply.fFrame": "Preferred design frame",
    "apply.phBizNo": "10-digit number",
    "apply.phMailOrder": "e.g. 2024-Seoul-Gangnam-1234",
    "apply.phCsPhone": "1588-0000 etc.",
    "apply.phReferrer": "Enter a referrer if you have one",
    "apply.phSlug": "lowercase letters/numbers/hyphens",
    "apply.framePlaceholder": "Select a frame",
    "apply.slugExampleWord": "store-name",
    "apply.exampleLabel": "Example",
    "apply.frameHintPre": "To see frames in detail, open the ",
    "apply.frameHintLink": "frames page",
    "apply.frameHintPost": " to preview them before choosing.",
    "apply.cancel": "Cancel",
    "apply.submit": "Submit application",
    "apply.submitting": "Submitting…",
    "apply.alertWarn": "Please check your entries. Some items are missing or in the wrong format.",
    "apply.agreeLabel": "I have read and agree to the free online store agreement above. (Required)",
    "apply.agreeError": "You must agree to the agreement",
    "apply.vBizName": "Please enter the business name",
    "apply.vBizNo": "Please enter the 10-digit business registration number",
    "apply.vCeoName": "Please enter the representative name",
    "apply.vCeoPhone": "Please check the representative phone number",
    "apply.vEmail": "Please check the email format",
    "apply.vMgrName": "Please enter the contact person name",
    "apply.vMgrPhone": "Please check the contact person phone number",
    "apply.vSlug": "3–30 lowercase letters/numbers/hyphens (start and end with alphanumeric)",
    "apply.vFrame": "Please select one frame",
    "apply.vAgreed": "You must agree to the agreement",
    "apply.tCheckInput": "Please check your entries",
    "apply.tSuccess": "Your application has been received",
    "apply.tDupSlug": "This URL name is already in use",
    "apply.tError": "An error occurred during submission",
    "apply.tServerError": "Submission failed due to a server error",
    "manual.title": "Admin Page Guide",
    "faq.title": "Frequently asked questions",
    "faq.desc": "Common questions from merchants, sorted into payments & settlement and store operations.",
    "faq.catPay": "Payments · PG · Settlement",
    "faq.catShop": "Store operations",
    "faq.notFound": "Didn't find the answer you were looking for?",
    "faq.askShop": "Store feature inquiries",
    "faq.askPay": "Partnership & payment inquiries",
    "faq.p1.q": "How does online payment work on SHOPGO?",
    "faq.p1.a": "SHOPGO is integrated with a PG (Payment Gateway) so payments are processed securely. Customers can order with a range of payment methods, and once payment completes the order details are sent to the seller automatically.",
    "faq.p2.q": "Which PGs (payment gateways) does SHOPGO support?",
    "faq.p2.a": "At launch, PayLetter and NICE are supported. NHN KCP, KICC, KSNET and other domestic and global PGs will follow. SHOPGO keeps adding PG providers so sellers can choose the payment setup they want.",
    "faq.p3.q": "Which payment methods can customers use?",
    "faq.p3.a": "Depending on the PG you choose: credit and debit cards, bank transfer, easy payments (KakaoPay, Naver Pay, Samsung Pay), foreign-issued cards (Visa, Mastercard, JCB, UnionPay, Amex) and overseas easy payments (WeChat Pay, Alipay, LINE Pay). Available methods differ slightly by PG.",
    "faq.p4.q": "Is a PG contract required?",
    "faq.p4.a": "Yes. A PG contract is required to accept online and mobile payments. SHOPGO supports the whole process — application, review, contract and store integration.",
    "faq.p5.q": "How long does PG review take?",
    "faq.p5.a": "Usually about 2-3 business weeks. It can vary with your industry and the documents submitted.",
    "faq.p6.q": "How much are the payment fees?",
    "faq.p6.a": "Fees depend on the PG you choose and your industry. We will confirm the exact rate once PG review is complete.",
    "faq.p7.q": "How is settlement handled?",
    "faq.p7.a": "Once a customer completes payment, funds are settled to the seller under the contracted PG's settlement policy. Settlement cycle and payout date follow each PG's policy.",
    "faq.p8.q": "Can overseas customers pay?",
    "faq.p8.a": "Yes. With a supported PG, customers can use foreign-issued cards (Visa, Mastercard, JCB, UnionPay, Amex) and overseas easy payments (WeChat Pay, Alipay, LINE Pay).",
    "faq.p9.q": "Can I change or add a PG later?",
    "faq.p9.a": "Yes. You can add or switch PGs as your business and operations change, and SHOPGO supports the integration.",
    "faq.p10.q": "Who do I contact about payment or settlement problems?",
    "faq.p10.a": "For approvals, cancellations, settlement, fees and other payment matters, contact SHOPGO support or your sales representative and we will help promptly. (Partnership & payment: office@forspay.com)",
    "faq.p11.q": "The store is free — is the payment service free too?",
    "faq.p11.a": "Using the SHOPGO store is free. PG payment processing is a financial service, so the contracted PG's payment fees and related costs apply separately.",
    "faq.p12.q": "Where can I see my PG transaction records?",
    "faq.p12.a": "You can view and print them directly on the transaction page your contracted PG provides. The lookup pages for the PGs in use are below.",
    "faq.s1.q": "How is my store address (domain) decided?",
    "faq.s1.a": "An address in the form 'yourstore.shopgo.co.kr' is created automatically from the name you request when applying. You can run your store right away without buying a domain.",
    "faq.s2.q": "How do I get my admin account?",
    "faq.s2.a": "When your store is approved, an email is sent with the admin page address, ID and initial password. The initial password is the same as the ID, so after signing in please change it under the profile menu at the top right.",
    "faq.s3.q": "How do I register products?",
    "faq.s3.a": "Go to Admin → Products → Add product and enter the name, price, main image, options and stock. A category must exist before you can add a product, so create one under Products first.",
    "faq.s4.q": "I want to hide a product for a while.",
    "faq.s4.a": "Set the product's status to 'Hidden' in the product list and it will no longer appear in the store. You can switch it back to 'On sale' at any time.",
    "faq.s5.q": "How do I show a discounted price?",
    "faq.s5.a": "Tick 'Show discount' when adding or editing a product and a 'price before discount' field appears. Enter a price higher than the selling price and the store shows a strikethrough with the discount percentage.",
    "faq.s6.q": "How do I check orders and enter tracking numbers?",
    "faq.s6.a": "Check incoming orders and change their status under Admin → Orders. After shipping, choose the courier and save the tracking number — the buyer's order history then shows the courier, tracking number and a tracking link.",
    "faq.s7.q": "How do I set shipping fees?",
    "faq.s7.a": "Set the base shipping fee and the free-shipping threshold under Settings → Shipping. Orders at or above the threshold ship free. If you set no shipping fee, shipping is treated as free.",
    "faq.s8.q": "Where do I manage members?",
    "faq.s8.a": "Under Admin → Members you can look up registered members and change their status or password. You can search by member ID, name or phone number.",
    "faq.s9.q": "Are there notice and inquiry boards?",
    "faq.s9.a": "A notice board and a 1:1 inquiry board are provided by default. Only the author and the administrator can see a 1:1 inquiry, and saving a reply on an inquiry posts that reply to the customer.",
    "faq.s10.q": "Where can I read the operating manual?",
    "faq.s10.a": "Use the manual link in your store-opening email, or the manual page on shopgo.co.kr. It walks first-time users through everything in order, from adding products to handling orders and shipping.",
    "manual.preApply": "Haven't applied yet?",
    "manual.applyLink": "Apply for a free online store",
    "complete.title": "Your application has been received",
    "complete.desc1": "Our team will review it |and contact you at the number you provided",
    "complete.desc2": "Once approved, your store will open |under the store name you requested",
    "complete.home": "Go home",
    "complete.manual": "Get the admin manual",
    "frame.shop:1.title": "Browse-Focused",
    "frame.shop:1.keyword": "Many categories",
    "frame.shop:1.desc": "A store where many products are easy and quick to find\nBrowse with the top category menu, and see the full-width slide banner alongside popular and almost-sold-out items at a glance",
    "frame.shop:1.recommend": "General stores (electronics, household goods, food, etc.)",
    "frame.shop:2.title": "Visual-Focused",
    "frame.shop:2.keyword": "Single brand",
    "frame.shop:2.desc": "A store that conveys your brand's image and mood\nA large main banner carries the brand and seasonal feel, while a pared-back top menu keeps the focus on the products and visuals",
    "frame.shop:2.recommend": "Single- or few-brand stores such as cosmetics and fashion",
    "frame.shop:4.title": "Multi-category Goods Mall",
    "frame.shop:4.keyword": "Fashion & goods, many items",
    "frame.shop:4.desc": "Arranges product grids by category in a rich layout\nDisplays items sorted by type such as bags, watches, shoes, and accessories",
    "frame.shop:4.recommend": "Goods malls with many categories and varied SKUs (bags, watches, shoes, accessories, etc.)",
    "frame.blog:1.title": "Magazine",
    "frame.blog:1.keyword": "Designer select shop",
    "frame.blog:1.desc": "A store that presents products and brand stories with style\n“Cover Story” and “Editor’s Pick” sections introduce products like a magazine, and a large banner makes even a single product feel rich and prominent",
    "frame.blog:1.recommend": "Fashion, jewelry, accessories, designer brands",
    "frame.blog:2.title": "Scroll",
    "frame.blog:2.keyword": "Single-column curation",
    "frame.blog:2.desc": "A simple store that is pleasant to browse\nProducts are laid out category by category in a single column, so customers can scroll comfortably on mobile",
    "frame.blog:2.recommend": "Curated select shops with a modest catalog\n※ For stores with many products, we recommend the Browse-Focused frame.",
    "frame.blog:4.title": "Premium Editorial",
    "frame.blog:4.keyword": "One or few categories",
    "frame.blog:4.desc": "A store that presents a single product like a work of art\nLarge visuals and a magazine layout emphasise the product’s value and detail, while monochrome tones and restrained typography create a refined mood",
    "frame.blog:4.recommend": "Premium design furniture, limited-edition brands",
    "frame.blog:5.title": "Dark Luxury",
    "frame.blog:5.keyword": "Premium & limited-edition brand",
    "frame.blog:5.desc": "A dark-toned background for a restrained, upscale, mysterious mood\nCopy that conveys brand heritage",
    "frame.blog:5.recommend": "Luxury bedding and living goods, premium brands, limited collections",
    "frame.blog:6.title": "Trustworthy Single Brand",
    "frame.blog:6.keyword": "Few items · trust-focused",
    "frame.blog:6.desc": "A tidy, clean layout\nBuilds trust step by step with trust points, statistics, and a gallery",
    "frame.blog:6.recommend": "Single/few-SKU brands (bottled water, supplements, a single cosmetics line, everyday consumables, etc.)",
    "frame.blog:7.title": "Eastern Minimal",
    "frame.blog:7.keyword": "Tea · herbal · naturalist",
    "frame.blog:7.desc": "Beige tones + Chinese-character keywords\nCalm copy with a Japanese/Eastern aesthetic",
    "frame.blog:7.recommend": "Tea/herbal tea, traditional foods, naturalist cosmetics, handcrafted lifestyle",
    "frame.blog:8.title": "Trendy Graphic",
    "frame.blog:8.keyword": "New arrivals for Gen MZ",
    "frame.blog:8.desc": "Vivid colors + monochrome block divisions\nBold copy with a trendy, refined graphic mood",
    "frame.blog:8.recommend": "New/limited-edition products targeting Gen MZ (indie beauty, sneakers, healthcare, trendy accessories, etc.)",
    "frame.blog:9.title": "Pastel Mood",
    "frame.blog:9.keyword": "One or few categories",
    "frame.blog:9.desc": "A store with a soft, warm atmosphere\nPink and pastel tones with a Polaroid feel present products and reviews naturally, for a friendly and stylish mood",
    "frame.blog:9.recommend": "Perfume, cosmetics, accessories, candles, diffusers",
  },
  ja: {
    "frames.title": "無料ショップ フレーム",
    "frames.desc1": "ブランドや業種に合った|さまざまなショップフレームからお選びください",
    "frames.desc2": "プレビューで実際のデザインと画面構成を|ご確認いただけます",
    "frames.noticeContent": "プレビューの商品・カテゴリー・バナーは例示です。開設後にご自身で設定できます",
    "frames.recommendLabel": "おすすめ業種",
    "frames.preview": "プレビュー",
    "frames.comingSoon": "準備中",
    "frames.applyBtn": "このフレームで申し込む",
    "frames.ctaLine1": "お気に入りのフレームが決まったら、",
    "frames.ctaLine2": "あとは申し込むだけで、|すべての準備が完了します",
    "frames.groupNote": "フレームごとにホーム・商品画面のデザインが異なり、注文・決済など主要機能の画面は共通です",
    "frames.group.shop.title": "ショップ型 · フレーム1〜2",
    "frames.group.shop.short": "ショップ型",
    "frames.group.shop.desc": "上部カテゴリーメニューと商品一覧ページを備えた構成です。カテゴリーや商品数が多いショップに向いています。",
    "frames.group.column.title": "ブログ型 · フレーム3〜4",
    "frames.group.column.short": "ブログ型",
    "frames.group.column.desc": "モバイルに合わせた狭い1カラム構成です。ホームと商品ページの雰囲気がフレームごとに異なります。",
    "frames.group.landing.title": "単一・少数商品ランディング型 · フレーム5〜6",
    "frames.group.landing.short": "単一・少数商品型",
    "frames.group.landing.desc": "代表商品を1〜2点大きく見せるランディング構成です。2つのフレームはホームと商品ページのデザイン・色味が異なり、カート・注文・マイページの画面は同じです。",
    "apply.title": "オンラインショップ申込書",
    "apply.desc": "ご入力いただいた内容を確認後、担当者からご連絡いたします。すべての必須項目をご入力のうえ、契約書にご同意ください。",
    "apply.sec1": "01 · 事業者情報",
    "apply.sec2": "02 · 代表者情報",
    "apply.sec3": "03 · 担当者情報",
    "apply.sec4": "04 · 運営情報",
    "apply.sec5": "05 · ショップアドレス（店舗名）",
    "apply.sec6": "06 · フレーム選択",
    "apply.sec7": "07 · 契約書",
    "apply.fBizName": "事業者名",
    "apply.fBizNo": "事業者番号",
    "apply.fMailOrder": "通信販売業届出番号",
    "apply.fCeoName": "代表者名",
    "apply.fCeoPhone": "代表者連絡先",
    "apply.fCeoEmail": "代表者メールアドレス",
    "apply.fMgrName": "担当者名",
    "apply.fMgrPhone": "担当者連絡先",
    "apply.fMgrEmail": "担当者メールアドレス",
    "apply.fCsPhone": "カスタマーセンター番号",
    "apply.fReferrer": "営業紹介者",
    "apply.fSlug": "ご利用になる店舗名",
    "apply.fFrame": "ご希望のデザインフレーム",
    "apply.phBizNo": "10桁の数字",
    "apply.phMailOrder": "例: 2024-東京渋谷-1234",
    "apply.phCsPhone": "1588-0000 など",
    "apply.phReferrer": "紹介者がいる場合はご入力ください",
    "apply.phSlug": "半角英小文字／数字／ハイフン",
    "apply.framePlaceholder": "フレーム選択",
    "apply.slugExampleWord": "店舗名",
    "apply.exampleLabel": "例",
    "apply.frameHintPre": "フレームを詳しく見るには",
    "apply.frameHintLink": "フレームページ",
    "apply.frameHintPost": "を開き、プレビューしてから選択してください。",
    "apply.cancel": "キャンセル",
    "apply.submit": "申込書を送信",
    "apply.submitting": "受付中…",
    "apply.alertWarn": "入力内容をご確認ください。未入力または形式が正しくない項目があります。",
    "apply.agreeLabel": "上記の無料ネットショップ提供契約書の内容を確認し、これに同意します。（必須）",
    "apply.agreeError": "契約書への同意が必要です",
    "apply.vBizName": "事業者名をご入力ください",
    "apply.vBizNo": "事業者番号10桁をご入力ください",
    "apply.vCeoName": "代表者名をご入力ください",
    "apply.vCeoPhone": "代表者連絡先をご確認ください",
    "apply.vEmail": "メールアドレスの形式をご確認ください",
    "apply.vMgrName": "担当者名をご入力ください",
    "apply.vMgrPhone": "担当者連絡先をご確認ください",
    "apply.vSlug": "半角英小文字／数字／ハイフン3～30文字（先頭・末尾は英数字）",
    "apply.vFrame": "フレームを1つ選択してください",
    "apply.vAgreed": "契約書への同意が必要です",
    "apply.tCheckInput": "入力内容をご確認ください",
    "apply.tSuccess": "お申し込みを受け付けました",
    "apply.tDupSlug": "すでに使用されているURL名です",
    "apply.tError": "受付中にエラーが発生しました",
    "apply.tServerError": "サーバーエラーにより受付に失敗しました",
    "manual.title": "管理者ページガイド",
    "faq.title": "よくあるご質問",
    "faq.desc": "加盟店の運営でよくいただくご質問を、決済・精算とショップ運営に分けてまとめました。",
    "faq.catPay": "決済 · PG · 精算",
    "faq.catShop": "ショップ運営",
    "faq.notFound": "お探しの答えが見つかりませんでしたか？",
    "faq.askShop": "ショップ機能に関するお問い合わせ",
    "faq.askPay": "加盟・決済に関するお問い合わせ",
    "faq.p1.q": "SHOPGOのオンライン決済はどのように行われますか？",
    "faq.p1.a": "SHOPGOはPG（Payment Gateway）と連携し、安全に決済が行われます。お客様はさまざまな決済手段でご注文でき、決済が完了すると注文情報が販売者へ自動的に送られます。",
    "faq.p2.q": "SHOPGOはどのPG（決済代行会社）に対応していますか？",
    "faq.p2.a": "サービス開始時点ではPayLetterとNICEに対応しており、NHN KCP・KICC・KSNETほか国内外のPGに順次対応予定です。SHOPGOは対応PGを継続的に増やし、販売者が希望する決済環境を選べるようにしています。",
    "faq.p3.q": "利用できる決済手段は何ですか？",
    "faq.p3.a": "選択したPGにより、クレジット・デビットカード、口座振替、簡単決済（KakaoPay・Naver Pay・Samsung Pay）、海外発行カード（Visa・Mastercard・JCB・UnionPay・Amex）、海外簡単決済（WeChat Pay・Alipay・LINE Pay）がご利用いただけます。提供される手段はPGごとに一部異なります。",
    "faq.p4.q": "PG契約は必ず必要ですか？",
    "faq.p4.a": "はい。オンライン（モバイル）決済のご利用にはPG契約が必要です。SHOPGOでは申込から審査、契約、ショップ連携まで全過程をサポートいたします。",
    "faq.p5.q": "PG審査はどのくらいかかりますか？",
    "faq.p5.a": "一般的に営業日ベースで2〜3週間ほどです。業種や提出書類により期間が変わることがあります。",
    "faq.p6.q": "決済手数料はいくらですか？",
    "faq.p6.a": "決済手数料は選択したPGと業種により異なります。正確な料率はPG審査の完了後にご案内いたします。",
    "faq.p7.q": "精算はどのように行われますか？",
    "faq.p7.a": "お客様の決済完了後、契約したPGの精算ポリシーに従って販売者へ精算されます。精算サイクルと支払日はPGごとのポリシーによります。",
    "faq.p8.q": "海外のお客様も決済できますか？",
    "faq.p8.a": "可能です。対応PGを選択すると、海外発行カード（Visa・Mastercard・JCB・UnionPay・Amex）および海外簡単決済（WeChat Pay・Alipay・LINE Pay）をご利用いただけます。",
    "faq.p9.q": "PGを変更したり追加したりできますか？",
    "faq.p9.a": "可能です。事業規模や運営環境に合わせて他のPGを追加・変更でき、SHOPGOが連携をサポートします。",
    "faq.p10.q": "決済や精算で問題が起きたらどこへ問い合わせますか？",
    "faq.p10.a": "決済の承認・キャンセル・精算・手数料など決済に関するお問い合わせは、SHOPGOカスタマーセンターまたは担当営業までお寄せください。迅速に対応いたします。（加盟・決済：office@forspay.com）",
    "faq.p11.q": "無料ショップですが決済サービスも無料ですか？",
    "faq.p11.a": "SHOPGOショップのご利用は無料です。ただしPG決済サービスは金融サービスのため、契約したPGの決済手数料および関連費用は別途適用されます。",
    "faq.p12.q": "PGの決済履歴はどこで確認しますか？",
    "faq.p12.a": "契約したPGが提供する取引履歴ページで直接ご確認・印刷いただけます。ご利用中のPGの照会ページは以下のとおりです。",
    "faq.s1.q": "ショップのアドレス（ドメイン）はどう決まりますか？",
    "faq.s1.a": "お申し込み時にご希望の名前で「店舗名.shopgo.co.kr」の形式のアドレスが自動生成されます。ドメインを購入せずにすぐショップを運営できます。",
    "faq.s2.q": "管理者アカウントはどう受け取りますか？",
    "faq.s2.a": "開設の承認時に、管理者ページのアドレス・ID・初期パスワードをご案内メールでお送りします。初期パスワードはIDと同じですので、ログイン後に右上のプロフィールから必ず変更してください。",
    "faq.s3.q": "商品はどのように登録しますか？",
    "faq.s3.a": "管理者ページ → 商品管理 → 商品追加で、商品名・販売価格・メイン画像・オプション・在庫を入力して登録します。商品登録にはカテゴリーが先に必要ですので、商品管理でカテゴリーを作成してからご登録ください。",
    "faq.s4.q": "商品を一時的に隠したいのですが。",
    "faq.s4.a": "商品一覧でその商品の状態を「非公開（非表示）」に変えるとショップに表示されなくなります。いつでも「販売中」に戻せます。",
    "faq.s5.q": "割引価格はどう表示しますか？",
    "faq.s5.a": "商品の登録・修正で「割引を表示する」にチェックすると「割引前の価格」の入力欄が現れます。販売価格より高い価格を入力すると、ショップに取り消し線と割引率（％）が表示されます。",
    "faq.s6.q": "注文の確認と送り状番号の入力はどうしますか？",
    "faq.s6.a": "管理者ページ → 注文管理で届いた注文を確認し、状態を変更します。発送後に配送会社を選んで送り状番号を保存すると、購入者の注文履歴に配送会社・送り状番号と「配送照会」リンクが表示されます。",
    "faq.s7.q": "送料はどのように設定しますか？",
    "faq.s7.a": "設定管理 → 送料設定で基本送料と送料無料の基準金額を設定します。基準金額以上のご注文は送料無料となり、送料を設定しない場合は送料無料として扱われます。",
    "faq.s8.q": "会員管理はどこで行いますか？",
    "faq.s8.a": "管理者ページ → 会員管理で登録会員を照会し、状態変更やパスワード変更などを行えます。会員ID・氏名・電話番号で検索できます。",
    "faq.s9.q": "お知らせ・お問い合わせ掲示板はありますか？",
    "faq.s9.a": "開設時にお知らせと1:1お問い合わせ掲示板が標準で提供されます。1:1お問い合わせは投稿者本人と管理者のみが閲覧でき、お問い合わせに返信を書いて保存するとお客様に返信が登録されます。",
    "faq.s10.q": "運営マニュアルはどこで見られますか？",
    "faq.s10.a": "開設案内メールのマニュアルリンク、またはshopgo.co.krのマニュアルページで管理者ガイドをご確認いただけます。初めての方向けに、商品登録から注文・配送処理まで順を追ってご案内しています。",
    "manual.preApply": "まだお申し込み前ですか？",
    "manual.applyLink": "無料ネットショップを申し込む",
    "complete.title": "お申し込みを受け付けました",
    "complete.desc1": "担当者が確認のうえ、|ご入力の連絡先へご連絡いたします",
    "complete.desc2": "承認が完了すると、|お申し込みの店舗名でショップが開設されます",
    "complete.home": "ホームへ",
    "complete.manual": "管理者マニュアルを入手",
    "frame.shop:1.title": "探索重視型",
    "frame.shop:1.keyword": "多カテゴリー",
    "frame.shop:1.desc": "多くの商品を簡単に素早く探せるショップ\n上部のカテゴリーメニューで目的の商品をすばやく探し、全幅スライドバナーと人気商品・残りわずかの商品を一目で確認できます",
    "frame.shop:1.recommend": "総合ショップ（家電・雑貨・食品など）",
    "frame.shop:2.title": "ビジュアル重視型",
    "frame.shop:2.keyword": "単一ブランド",
    "frame.shop:2.desc": "ブランドのイメージと世界観を効果的に伝えるショップ\n大きなメインバナーでブランドとシーズンの雰囲気を強調し、上部メニューを簡潔にして商品とビジュアルに集中できます",
    "frame.shop:2.recommend": "化粧品・ファッションなど単一／少数ブランドの店舗",
    "frame.shop:4.title": "多カテゴリー雑貨モール",
    "frame.shop:4.keyword": "ファッション・雑貨の多品目",
    "frame.shop:4.desc": "カテゴリーごとの商品グリッドを多彩に配置\nバッグ・時計・靴・アクセサリーなど種類別に分類して陳列",
    "frame.shop:4.recommend": "カテゴリーが多くSKUが豊富な雑貨モール（バッグ・時計・靴・アクセサリーなど）",
    "frame.blog:1.title": "マガジン型",
    "frame.blog:1.keyword": "デザイナーセレクトショップ",
    "frame.blog:1.desc": "商品とブランドストーリーを感性豊かに見せるショップ\n「Cover Story」「Editor’s Pick」の構成で商品を雑誌のように紹介し、大きなバナーで一つの商品も豊かに際立たせられます",
    "frame.blog:1.recommend": "ファッション、ジュエリー、アクセサリー、デザイナーブランド",
    "frame.blog:2.title": "スクロール型",
    "frame.blog:2.keyword": "1カラムキュレーション",
    "frame.blog:2.desc": "商品を自然に見て回れるシンプルなショップ\nカテゴリーごとの商品を1カラムに順に並べ、モバイルでスクロールしながら快適に見て回れます",
    "frame.blog:2.recommend": "商品数が多くないキュレーション・セレクトショップ\n※ 商品数が多い場合は探索重視型をおすすめします。",
    "frame.blog:4.title": "プレミアム エディトリアル型",
    "frame.blog:4.keyword": "単一・少数カテゴリー",
    "frame.blog:4.desc": "一つの商品を作品のように際立たせるショップ\n大きなビジュアルとマガジン風レイアウトで商品の価値とディテールを強調し、モノトーンと抑制されたタイポグラフィで上質で洗練された雰囲気を演出します",
    "frame.blog:4.recommend": "プレミアムデザイン家具・限定エディションブランド",
    "frame.blog:5.title": "ダークラグジュアリー",
    "frame.blog:5.keyword": "高級・限定版ブランド",
    "frame.blog:5.desc": "ダークトーンの背景で抑制・高級・神秘的なムード\nブランドヘリテージを込めたコピー",
    "frame.blog:5.recommend": "ラグジュアリー寝具・生活用品、プレミアムブランド、限定コレクション",
    "frame.blog:6.title": "信頼型単一ブランド",
    "frame.blog:6.keyword": "少数品目・信頼型",
    "frame.blog:6.desc": "整った清潔なレイアウト\n信頼ポイント・統計・ギャラリーで信頼を段階的に伝達",
    "frame.blog:6.recommend": "単一／少数SKUブランド（ミネラルウォーター・サプリメント、単一化粧品ライン、日用消費財など）",
    "frame.blog:7.title": "東洋ミニマル",
    "frame.blog:7.keyword": "茶・漢方・ナチュラル志向",
    "frame.blog:7.desc": "ベージュトーン＋漢字キーワード\n落ち着いたコピー、日本・東洋の美意識",
    "frame.blog:7.recommend": "茶／漢方茶、伝統食品、ナチュラル志向の化粧品、手工芸ライフスタイル",
    "frame.blog:8.title": "トレンディグラフィック",
    "frame.blog:8.keyword": "Z世代ターゲット新商品",
    "frame.blog:8.desc": "ビビッドカラー＋モノクロームのブロック分割\n強いコピー、トレンディで洗練されたグラフィックムード",
    "frame.blog:8.recommend": "Z世代ターゲットの新商品／限定版（インディーズビューティー、スニーカー、ヘルスケア、トレンディなアクセサリーなど）",
    "frame.blog:9.title": "パステル調",
    "frame.blog:9.keyword": "単一・少数カテゴリー",
    "frame.blog:9.desc": "やわらかく温かい雰囲気で商品を見せるショップ\nピンク・パステルトーンとポラロイド感で商品とレビューを自然に表現し、親しみやすく感度の高い雰囲気を演出します",
    "frame.blog:9.recommend": "香水・化粧品・アクセサリー・キャンドル・ディフューザー",
  },
  cn: {
    "frames.title": "免费商城框架",
    "frames.desc1": "请选择适合您品牌与行业的商城框架",
    "frames.desc2": "可通过预览查看实际设计与页面结构",
    "frames.noticeContent": "预览中的商品·分类·横幅均为示例，开通后可自行设置",
    "frames.recommendLabel": "推荐行业",
    "frames.preview": "预览",
    "frames.comingSoon": "敬请期待",
    "frames.applyBtn": "使用此框架申请",
    "frames.ctaLine1": "如果您已选好心仪的框架，",
    "frames.ctaLine2": "现在只需提交申请，一切准备即可就绪",
    "frames.groupNote": "各框架的首页与商品页设计不同，下单·支付等主要功能页面完全相同",
    "frames.group.shop.title": "商城型 · 框架1–2",
    "frames.group.shop.short": "商城型",
    "frames.group.shop.desc": "配有顶部品类菜单和商品列表页的结构，适合品类和商品数量较多的商城。",
    "frames.group.column.title": "博客型 · 框架3–4",
    "frames.group.column.short": "博客型",
    "frames.group.column.desc": "为移动端设计的窄单栏结构。首页和商品页的风格因框架而异。",
    "frames.group.landing.title": "单品·少量商品落地型 · 框架5–6",
    "frames.group.landing.short": "单品·少量商品型",
    "frames.group.landing.desc": "以一两件主打商品为核心的落地页结构。两个框架在首页和商品页的设计与配色上不同，购物车、订单和我的页面完全相同。",
    "apply.title": "网上商城申请表",
    "apply.desc": "确认您填写的内容后，专员将与您联系。请填写所有必填项并同意约定书。",
    "apply.sec1": "01 · 工商信息",
    "apply.sec2": "02 · 法人代表信息",
    "apply.sec3": "03 · 负责人信息",
    "apply.sec4": "04 · 运营信息",
    "apply.sec5": "05 · 商城地址（店铺名）",
    "apply.sec6": "06 · 框架选择",
    "apply.sec7": "07 · 约定书",
    "apply.fBizName": "企业名称",
    "apply.fBizNo": "营业执照号",
    "apply.fMailOrder": "网络销售业申报号",
    "apply.fCeoName": "法人代表姓名",
    "apply.fCeoPhone": "法人代表联系电话",
    "apply.fCeoEmail": "法人代表邮箱",
    "apply.fMgrName": "负责人姓名",
    "apply.fMgrPhone": "负责人联系电话",
    "apply.fMgrEmail": "负责人邮箱",
    "apply.fCsPhone": "客服中心电话",
    "apply.fReferrer": "业务推荐人",
    "apply.fSlug": "要使用的店铺名",
    "apply.fFrame": "您希望的设计框架",
    "apply.phBizNo": "10 位数字",
    "apply.phMailOrder": "例：2024-首尔江南-1234",
    "apply.phCsPhone": "1588-0000 等",
    "apply.phReferrer": "如有推荐人请填写",
    "apply.phSlug": "小写英文字母／数字／连字符",
    "apply.framePlaceholder": "选择框架",
    "apply.slugExampleWord": "店铺名",
    "apply.exampleLabel": "示例",
    "apply.frameHintPre": "如需查看框架详情，请打开",
    "apply.frameHintLink": "框架页面",
    "apply.frameHintPost": "预览后进行选择。",
    "apply.cancel": "取消",
    "apply.submit": "提交申请表",
    "apply.submitting": "受理中…",
    "apply.alertWarn": "请检查您的输入内容。存在遗漏或格式不正确的项目。",
    "apply.agreeLabel": "我已阅读上述免费商城提供约定书的内容，并表示同意。（必填）",
    "apply.agreeError": "需要同意约定书",
    "apply.vBizName": "请输入企业名称",
    "apply.vBizNo": "请输入 10 位营业执照号",
    "apply.vCeoName": "请输入法人代表姓名",
    "apply.vCeoPhone": "请核对法人代表联系电话",
    "apply.vEmail": "请核对邮箱格式",
    "apply.vMgrName": "请输入负责人姓名",
    "apply.vMgrPhone": "请核对负责人联系电话",
    "apply.vSlug": "小写英文字母／数字／连字符 3～30 位（首尾须为英文或数字）",
    "apply.vFrame": "请选择 1 个框架",
    "apply.vAgreed": "需要同意约定书",
    "apply.tCheckInput": "请检查输入内容",
    "apply.tSuccess": "申请已受理",
    "apply.tDupSlug": "该 URL 名称已被占用",
    "apply.tError": "受理过程中发生错误",
    "apply.tServerError": "因服务器错误受理失败",
    "manual.title": "管理员页面指南",
    "faq.title": "常见问题",
    "faq.desc": "我们将商家运营中的常见问题分为支付·结算与商城运营两部分整理如下。",
    "faq.catPay": "支付 · PG · 结算",
    "faq.catShop": "商城运营",
    "faq.notFound": "没有找到您想要的答案吗？",
    "faq.askShop": "商城功能咨询",
    "faq.askPay": "加盟及支付咨询",
    "faq.p1.q": "SHOPGO的在线支付是如何进行的？",
    "faq.p1.a": "SHOPGO与PG（Payment Gateway）对接，可安全完成支付。顾客可使用多种支付方式下单，支付完成后订单信息将自动发送给卖家。",
    "faq.p2.q": "SHOPGO支持哪些PG（支付代理公司）？",
    "faq.p2.a": "服务开放初期支持PayLetter与NICE，NHN KCP·KICC·KSNET及其他国内外PG将陆续支持。SHOPGO会持续扩充PG合作方，让卖家能选择所需的支付环境。",
    "faq.p3.q": "可以使用哪些支付方式？",
    "faq.p3.a": "视所选PG而定，可使用信用卡·借记卡、账户转账、简易支付（KakaoPay·Naver Pay·Samsung Pay）、境外发行卡（Visa·Mastercard·JCB·银联·Amex）以及境外简易支付（微信支付·支付宝·LINE Pay）。各PG提供的支付方式略有差异。",
    "faq.p4.q": "必须签订PG合同吗？",
    "faq.p4.a": "是的。使用在线（移动）支付需要签订PG合同。SHOPGO将全程协助您完成申请、审核、签约到商城对接。",
    "faq.p5.q": "PG审核需要多久？",
    "faq.p5.a": "通常需要2〜3个工作周，具体时长会因行业与提交材料而有所不同。",
    "faq.p6.q": "支付手续费是多少？",
    "faq.p6.a": "手续费取决于所选PG与行业类别。准确费率将在PG审核完成后告知。",
    "faq.p7.q": "结算是如何进行的？",
    "faq.p7.a": "顾客完成支付后，将按照签约PG的结算政策向卖家结算。结算周期与付款日以各PG的政策为准。",
    "faq.p8.q": "海外顾客也能付款吗？",
    "faq.p8.a": "可以。选择支持的PG后，可使用境外发行卡（Visa·Mastercard·JCB·银联·Amex）及境外简易支付（微信支付·支付宝·LINE Pay）。",
    "faq.p9.q": "可以更换或新增PG吗？",
    "faq.p9.a": "可以。您可根据业务规模与运营环境新增或更换PG，SHOPGO将协助完成对接。",
    "faq.p10.q": "支付或结算出现问题时联系谁？",
    "faq.p10.a": "支付授权、取消、结算、手续费等支付相关咨询，请联系SHOPGO客服中心或您的销售负责人，我们会尽快处理。（加盟及支付：office@forspay.com）",
    "faq.p11.q": "商城是免费的，支付服务也免费吗？",
    "faq.p11.a": "SHOPGO商城的使用是免费的。但PG支付服务属于金融服务，签约PG的支付手续费及相关费用需另行承担。",
    "faq.p12.q": "在哪里查看PG的支付明细？",
    "faq.p12.a": "可在签约PG提供的交易明细页面直接查看与打印。您正在使用的PG查询页面如下。",
    "faq.s1.q": "商城地址（域名）如何确定？",
    "faq.s1.a": "系统会根据申请时填写的名称自动生成“店铺名.shopgo.co.kr”形式的地址。无需另行购买域名即可立即运营商城。",
    "faq.s2.q": "如何获取管理员账号？",
    "faq.s2.a": "开通（审核通过）时会通过邮件发送管理后台地址、账号与初始密码。初始密码与账号相同，登录后请务必在右上角个人资料中修改。",
    "faq.s3.q": "如何登记商品？",
    "faq.s3.a": "进入管理后台 → 商品管理 → 添加商品，填写商品名、售价、主图、选项与库存后登记。登记商品前需先有分类，请在商品管理中先创建分类。",
    "faq.s4.q": "想暂时隐藏某个商品。",
    "faq.s4.a": "在商品列表中将该商品状态改为“不公开（隐藏）”，即不会在商城中显示。随时可以改回“销售中”。",
    "faq.s5.q": "如何显示折扣价？",
    "faq.s5.a": "在商品登记/修改中勾选“显示折扣”，会出现“折扣前价格（原价）”输入框。填入高于售价的原价后，商城将同时显示删除线与折扣率（%）。",
    "faq.s6.q": "如何确认订单并录入运单号？",
    "faq.s6.a": "在管理后台 → 订单管理中确认收到的订单并变更状态。发货后选择快递公司并保存运单号，购买者的订单记录中即会显示快递公司、运单号与“物流查询”链接。",
    "faq.s7.q": "运费如何设置？",
    "faq.s7.a": "在设置管理 → 运费设置中设定基本运费与免运费门槛金额。达到或超过门槛金额的订单免运费；若未设置运费，则按免运费处理。",
    "faq.s8.q": "在哪里管理会员？",
    "faq.s8.a": "在管理后台 → 会员管理中可查询已注册会员并变更其状态或密码。可按会员账号、姓名、电话号码搜索。",
    "faq.s9.q": "有公告和咨询板块吗？",
    "faq.s9.a": "开通时默认提供公告板与1:1咨询板。1:1咨询仅作者本人与管理员可见，在咨询帖中撰写并保存回复后，回复即会呈现给顾客。",
    "faq.s10.q": "在哪里查看运营手册？",
    "faq.s10.a": "可通过开通通知邮件中的手册链接，或shopgo.co.kr的手册页面查看管理员指南。其中面向新手，按顺序介绍了从商品登记到订单·配送处理的全过程。",
    "manual.preApply": "还未申请吗？",
    "manual.applyLink": "申请免费商城",
    "complete.title": "申请已受理",
    "complete.desc1": "专员将审核后通过您填写的联系方式与您联系",
    "complete.desc2": "审核通过后，将以您申请的店铺名开设网店",
    "complete.home": "返回首页",
    "complete.manual": "获取管理员手册",
    "frame.shop:1.title": "探索导向型",
    "frame.shop:1.keyword": "多品类",
    "frame.shop:1.desc": "让大量商品都能轻松快速找到的商城\n通过顶部分类菜单快速浏览，并可一眼看到全宽轮播横幅与热销·即将售罄商品",
    "frame.shop:1.recommend": "综合商城（家电·杂货·食品等）",
    "frame.shop:2.title": "视觉导向型",
    "frame.shop:2.keyword": "单一品牌",
    "frame.shop:2.desc": "有效展现品牌形象与调性的商城\n以大幅主横幅突出品牌与季节氛围，顶部菜单简洁，让顾客专注于商品与视觉",
    "frame.shop:2.recommend": "化妆品·时尚等单一／少量品牌门店",
    "frame.shop:4.title": "多品类杂货商城",
    "frame.shop:4.keyword": "时尚·杂货多品项",
    "frame.shop:4.desc": "按品类丰富排布商品网格\n按包袋、手表、鞋履、饰品等种类分类陈列",
    "frame.shop:4.recommend": "品类繁多、SKU 多样的杂货商城（包袋、手表、鞋履、饰品等）",
    "frame.blog:1.title": "杂志型",
    "frame.blog:1.keyword": "设计师买手店",
    "frame.blog:1.desc": "以感性方式呈现商品与品牌故事的商城\n通过“Cover Story”与“Editor’s Pick”像杂志一样介绍商品，并用大幅横幅让单件商品也丰富醒目",
    "frame.blog:1.recommend": "时尚、珠宝、饰品、设计师品牌",
    "frame.blog:2.title": "滚动型",
    "frame.blog:2.keyword": "单栏策展",
    "frame.blog:2.desc": "适合自然浏览商品的简约商城\n按分类将商品依次排在单栏中，在手机上滚动浏览十分顺畅",
    "frame.blog:2.recommend": "商品数量不多的策展·买手店\n※ 商品较多的商城建议选择探索导向型。",
    "frame.blog:4.title": "高端编辑型",
    "frame.blog:4.keyword": "单一·少量品类",
    "frame.blog:4.desc": "让单件商品如作品般突出的商城\n以大幅视觉与杂志式排版强调商品的价值与细节，并以黑白色调与克制的字体营造高级精致的氛围",
    "frame.blog:4.recommend": "高端设计家具·限量版品牌",
    "frame.blog:5.title": "暗黑奢华",
    "frame.blog:5.keyword": "高端·限量版品牌",
    "frame.blog:5.desc": "暗色调背景营造克制、高级、神秘的氛围\n融入品牌传承的文案",
    "frame.blog:5.recommend": "奢华寝具·生活用品、高端品牌、限量系列",
    "frame.blog:6.title": "信赖型单一品牌",
    "frame.blog:6.keyword": "少数品项 · 信赖型",
    "frame.blog:6.desc": "整洁规整的布局\n通过信赖要点、数据、图库逐步传递信任感",
    "frame.blog:6.recommend": "单一／少数 SKU 品牌（矿泉水、营养品、单一化妆品线、日常消费品等）",
    "frame.blog:7.title": "东方极简",
    "frame.blog:7.keyword": "茶·韩方·自然主义",
    "frame.blog:7.desc": "米色调 + 汉字关键词\n沉稳的文案，日式·东方美感",
    "frame.blog:7.recommend": "茶／韩方茶、传统食品、自然主义化妆品、手工艺生活方式",
    "frame.blog:8.title": "潮流图形",
    "frame.blog:8.keyword": "面向 Z 世代新品",
    "frame.blog:8.desc": "鲜艳配色 + 单色块面分割\n强烈文案，潮流·精致的图形氛围",
    "frame.blog:8.recommend": "面向 Z 世代的新品／限量版（独立美妆、球鞋、健康护理、潮流饰品等）",
    "frame.blog:9.title": "柔美粉彩型",
    "frame.blog:9.keyword": "单一·少量品类",
    "frame.blog:9.desc": "以柔和温暖氛围呈现商品的商城\n以粉色·马卡龙色调与拍立得质感自然呈现商品与评价，营造亲切而有格调的氛围",
    "frame.blog:9.recommend": "香水·化妆品·饰品·蜡烛·扩香",
  },
  es: {
    "frames.title": "Plantillas de tienda online gratuita",
    "frames.desc1": "Elija entre varias plantillas |que se ajusten a su marca y sector",
    "frames.desc2": "Use la vista previa para ver |el diseño y la disposición reales",
    "frames.noticeContent": "Los productos, categorías y banners de la vista previa son ejemplos; podrá configurarlos tras la apertura",
    "frames.recommendLabel": "Sector recomendado",
    "frames.preview": "Vista previa",
    "frames.comingSoon": "Próximamente",
    "frames.applyBtn": "Solicitar con esta plantilla",
    "frames.ctaLine1": "Si has elegido la plantilla |que te gusta,",
    "frames.ctaLine2": "ahora solo con la solicitud |todo queda listo",
    "frames.groupNote": "Las pantallas de inicio y producto cambian según la plantilla; los pedidos, pagos y demás funciones son iguales",
    "frames.group.shop.title": "Tipo tienda · Frames 1-2",
    "frames.group.shop.short": "Tipo tienda",
    "frames.group.shop.desc": "Diseño con menú de categorías superior y página de listado de productos. Ideal para tiendas con muchas categorías y productos.",
    "frames.group.column.title": "Tipo blog · Frames 3-4",
    "frames.group.column.short": "Tipo blog",
    "frames.group.column.desc": "Diseño de una columna estrecha pensado para móvil. El ambiente de la portada y las páginas de producto cambia según el frame.",
    "frames.group.landing.title": "Landing de uno o pocos productos · Frames 5-6",
    "frames.group.landing.short": "Pocos productos",
    "frames.group.landing.desc": "Diseño tipo landing que destaca uno o dos productos. Los dos frames difieren en el diseño y color de la portada y las páginas de producto; el carrito, el pedido y Mi cuenta son idénticos.",
    "apply.title": "Formulario de solicitud de tienda online",
    "apply.desc": "Tras revisar los datos introducidos, un responsable se pondrá en contacto contigo. Rellena todos los campos obligatorios y acepta el contrato.",
    "apply.sec1": "01 · Datos de la empresa",
    "apply.sec2": "02 · Datos del representante",
    "apply.sec3": "03 · Datos del responsable",
    "apply.sec4": "04 · Datos de operación",
    "apply.sec5": "05 · Dirección de la tienda (nombre de tienda)",
    "apply.sec6": "06 · Selección de plantilla",
    "apply.sec7": "07 · Contrato",
    "apply.fBizName": "Nombre de la empresa",
    "apply.fBizNo": "Número de empresa",
    "apply.fMailOrder": "Nº de registro de venta a distancia",
    "apply.fCeoName": "Nombre del representante",
    "apply.fCeoPhone": "Teléfono del representante",
    "apply.fCeoEmail": "Correo del representante",
    "apply.fMgrName": "Nombre del responsable",
    "apply.fMgrPhone": "Teléfono del responsable",
    "apply.fMgrEmail": "Correo del responsable",
    "apply.fCsPhone": "Número de atención al cliente",
    "apply.fReferrer": "Recomendador comercial",
    "apply.fSlug": "Nombre de tienda que usarás",
    "apply.fFrame": "Plantilla de diseño deseada",
    "apply.phBizNo": "10 dígitos numéricos",
    "apply.phMailOrder": "e.j.: 2024-Madrid-1234",
    "apply.phCsPhone": "1588-0000 etc.",
    "apply.phReferrer": "Si tienes un recomendador, introdúcelo",
    "apply.phSlug": "Minúsculas/números/guiones",
    "apply.framePlaceholder": "Seleccionar plantilla",
    "apply.slugExampleWord": "nombre-tienda",
    "apply.exampleLabel": "Ejemplo",
    "apply.frameHintPre": "Para ver las plantillas en detalle, abre la ",
    "apply.frameHintLink": "página de plantillas",
    "apply.frameHintPost": " y selecciona tras la vista previa.",
    "apply.cancel": "Cancelar",
    "apply.submit": "Enviar solicitud",
    "apply.submitting": "Procesando…",
    "apply.alertWarn": "Revisa los datos introducidos. Hay campos que faltan o con un formato incorrecto.",
    "apply.agreeLabel": "He leído el contenido del contrato de suministro de tienda online gratuita anterior y lo acepto. (obligatorio)",
    "apply.agreeError": "Es necesario aceptar el contrato",
    "apply.vBizName": "Introduce el nombre de la empresa",
    "apply.vBizNo": "Introduce los 10 dígitos del número de empresa",
    "apply.vCeoName": "Introduce el nombre del representante",
    "apply.vCeoPhone": "Comprueba el teléfono del representante",
    "apply.vEmail": "Comprueba el formato del correo",
    "apply.vMgrName": "Introduce el nombre del responsable",
    "apply.vMgrPhone": "Comprueba el teléfono del responsable",
    "apply.vSlug": "Minúsculas/números/guiones, 3~30 caracteres (inicio y fin alfanuméricos)",
    "apply.vFrame": "Selecciona una plantilla",
    "apply.vAgreed": "Es necesario aceptar el contrato",
    "apply.tCheckInput": "Revisa los datos introducidos",
    "apply.tSuccess": "Tu solicitud ha sido recibida",
    "apply.tDupSlug": "Este nombre de URL ya está en uso",
    "apply.tError": "Se ha producido un error durante el registro",
    "apply.tServerError": "El registro falló por un error del servidor",
    "manual.title": "Guía del panel de administración",
    "faq.title": "Preguntas frecuentes",
    "faq.desc": "Reunimos las preguntas más habituales de los comercios, separadas en pagos y liquidación, y gestión de la tienda.",
    "faq.catPay": "Pagos · PG · Liquidación",
    "faq.catShop": "Gestión de la tienda",
    "faq.notFound": "¿No encontró la respuesta que buscaba?",
    "faq.askShop": "Consultas sobre funciones de la tienda",
    "faq.askPay": "Consultas de afiliación y pagos",
    "faq.p1.q": "¿Cómo funcionan los pagos en línea en SHOPGO?",
    "faq.p1.a": "SHOPGO está integrado con una pasarela de pago (PG), por lo que los pagos se procesan de forma segura. Los clientes pueden pagar con distintos métodos y, al completarse el pago, los datos del pedido llegan automáticamente al vendedor.",
    "faq.p2.q": "¿Qué pasarelas de pago (PG) admite SHOPGO?",
    "faq.p2.a": "Al inicio del servicio se admiten PayLetter y NICE; NHN KCP, KICC, KSNET y otras pasarelas nacionales e internacionales se irán incorporando. SHOPGO amplía continuamente los proveedores para que el vendedor elija el entorno de pago que prefiera.",
    "faq.p3.q": "¿Qué métodos de pago se pueden usar?",
    "faq.p3.a": "Según la pasarela elegida: tarjetas de crédito y débito, transferencia bancaria, pagos rápidos (KakaoPay, Naver Pay, Samsung Pay), tarjetas emitidas en el extranjero (Visa, Mastercard, JCB, UnionPay, Amex) y pagos rápidos internacionales (WeChat Pay, Alipay, LINE Pay). Los métodos disponibles varían ligeramente según la pasarela.",
    "faq.p4.q": "¿Es obligatorio el contrato con una pasarela de pago?",
    "faq.p4.a": "Sí. Para aceptar pagos en línea y móviles se necesita un contrato con una pasarela. SHOPGO acompaña todo el proceso: solicitud, revisión, contrato e integración con la tienda.",
    "faq.p5.q": "¿Cuánto tarda la revisión de la pasarela?",
    "faq.p5.a": "Normalmente entre 2 y 3 semanas hábiles. El plazo puede variar según el sector y la documentación presentada.",
    "faq.p6.q": "¿Cuánto cuestan las comisiones de pago?",
    "faq.p6.a": "Dependen de la pasarela elegida y del sector. Le indicaremos la tarifa exacta una vez finalizada la revisión.",
    "faq.p7.q": "¿Cómo se realiza la liquidación?",
    "faq.p7.a": "Cuando el cliente completa el pago, el importe se liquida al vendedor según la política de la pasarela contratada. El ciclo de liquidación y la fecha de abono siguen la política de cada pasarela.",
    "faq.p8.q": "¿Pueden pagar clientes del extranjero?",
    "faq.p8.a": "Sí. Con una pasarela compatible se pueden usar tarjetas emitidas en el extranjero (Visa, Mastercard, JCB, UnionPay, Amex) y pagos rápidos internacionales (WeChat Pay, Alipay, LINE Pay).",
    "faq.p9.q": "¿Puedo cambiar o añadir una pasarela más adelante?",
    "faq.p9.a": "Sí. Puede añadir o cambiar de pasarela según crezca su negocio, y SHOPGO se encarga de la integración.",
    "faq.p10.q": "¿A quién consulto si hay un problema de pago o liquidación?",
    "faq.p10.a": "Para autorizaciones, cancelaciones, liquidaciones, comisiones y demás asuntos de pago, contacte con el servicio de atención de SHOPGO o con su comercial y le ayudaremos con rapidez. (Afiliación y pagos: office@forspay.com)",
    "faq.p11.q": "La tienda es gratuita, ¿el servicio de pago también?",
    "faq.p11.a": "El uso de la tienda SHOPGO es gratuito. El procesamiento de pagos es un servicio financiero, por lo que las comisiones y costes de la pasarela contratada se aplican aparte.",
    "faq.p12.q": "¿Dónde consulto los movimientos de la pasarela?",
    "faq.p12.a": "Puede consultarlos e imprimirlos directamente en la página de transacciones que ofrece su pasarela contratada. Las páginas de consulta de las pasarelas en uso son las siguientes.",
    "faq.s1.q": "¿Cómo se decide la dirección (dominio) de mi tienda?",
    "faq.s1.a": "Se genera automáticamente una dirección del tipo «nombredetienda.shopgo.co.kr» a partir del nombre solicitado. Puede empezar a operar sin comprar ningún dominio.",
    "faq.s2.q": "¿Cómo recibo mi cuenta de administrador?",
    "faq.s2.a": "Al aprobarse la apertura le enviamos por correo la dirección del panel, el ID y la contraseña inicial. La contraseña inicial coincide con el ID, así que cámbiela tras iniciar sesión desde el menú de perfil, arriba a la derecha.",
    "faq.s3.q": "¿Cómo doy de alta productos?",
    "faq.s3.a": "Vaya a Admin → Productos → Añadir producto e introduzca nombre, precio, imagen principal, opciones y stock. Antes debe existir una categoría, así que créela primero en Productos.",
    "faq.s4.q": "Quiero ocultar un producto temporalmente.",
    "faq.s4.a": "Cambie el estado del producto a «Oculto» en la lista de productos y dejará de mostrarse en la tienda. Puede volver a «A la venta» cuando quiera.",
    "faq.s5.q": "¿Cómo muestro un precio rebajado?",
    "faq.s5.a": "Marque «Mostrar descuento» al crear o editar el producto y aparecerá el campo «precio antes del descuento». Si introduce un precio superior al de venta, la tienda mostrará el tachado junto al porcentaje de descuento.",
    "faq.s6.q": "¿Cómo consulto pedidos e introduzco el número de seguimiento?",
    "faq.s6.a": "Revise los pedidos entrantes y cambie su estado en Admin → Pedidos. Tras el envío, elija la empresa de transporte y guarde el número de seguimiento: el historial del comprador mostrará el transportista, el número y un enlace de seguimiento.",
    "faq.s7.q": "¿Cómo configuro los gastos de envío?",
    "faq.s7.a": "Configure el envío base y el importe mínimo para envío gratuito en Ajustes → Envío. Los pedidos que alcancen ese importe se envían gratis; si no configura ningún importe, el envío se trata como gratuito.",
    "faq.s8.q": "¿Dónde gestiono a los miembros?",
    "faq.s8.a": "En Admin → Miembros puede consultar a los miembros registrados y cambiar su estado o contraseña. Puede buscar por ID, nombre o número de teléfono.",
    "faq.s9.q": "¿Hay tablones de avisos y consultas?",
    "faq.s9.a": "Se incluyen de serie un tablón de avisos y otro de consultas 1:1. Solo el autor y el administrador ven una consulta 1:1, y al guardar una respuesta esta queda publicada para el cliente.",
    "faq.s10.q": "¿Dónde puedo leer el manual de uso?",
    "faq.s10.a": "En el enlace al manual del correo de apertura o en la página de manual de shopgo.co.kr. Guía paso a paso a quienes empiezan, desde dar de alta productos hasta gestionar pedidos y envíos.",
    "manual.preApply": "¿Aún no has solicitado?",
    "manual.applyLink": "Solicitar tienda online gratuita",
    "complete.title": "Tu solicitud ha sido recibida",
    "complete.desc1": "Nuestro equipo la revisará |y te contactará al número que indicaste",
    "complete.desc2": "Una vez aprobada, tu tienda se abrirá |con el nombre de tienda que solicitaste",
    "complete.home": "Ir al inicio",
    "complete.manual": "Obtener el manual del administrador",
    "frame.shop:1.title": "Enfoque en navegación",
    "frame.shop:1.keyword": "Muchas categorías",
    "frame.shop:1.desc": "Una tienda donde encontrar muchos productos es fácil y rápido\nNavegue con el menú superior de categorías y vea de un vistazo el banner a todo el ancho junto a los productos populares y casi agotados",
    "frame.shop:1.recommend": "Tiendas generalistas (electrónica, hogar, alimentación, etc.)",
    "frame.shop:2.title": "Enfoque visual",
    "frame.shop:2.keyword": "Marca única",
    "frame.shop:2.desc": "Una tienda que transmite la imagen y el carácter de su marca\nUn gran banner principal marca el tono de la marca y la temporada, y un menú superior sobrio mantiene la atención en los productos",
    "frame.shop:2.recommend": "Tiendas de una o pocas marcas, como cosmética y moda",
    "frame.shop:4.title": "Tienda de artículos multicategoría",
    "frame.shop:4.keyword": "Moda y artículos variados",
    "frame.shop:4.desc": "Distribuye de forma variada la cuadrícula de productos por categoría\nExhibición clasificada por tipos: bolsos, relojes, zapatos, accesorios, etc.",
    "frame.shop:4.recommend": "Tiendas de artículos varios con muchas categorías y SKU diversos (bolsos, relojes, zapatos, accesorios, etc.)",
    "frame.blog:1.title": "Tipo revista",
    "frame.blog:1.keyword": "Tienda selecta de diseñador",
    "frame.blog:1.desc": "Una tienda que presenta productos e historias de marca con estilo\nLas secciones «Cover Story» y «Editor’s Pick» presentan los productos como una revista, y un gran banner hace que incluso un solo producto luzca",
    "frame.blog:1.recommend": "Moda, joyería, accesorios, marcas de diseñador",
    "frame.blog:2.title": "Tipo scroll",
    "frame.blog:2.keyword": "Curación en una columna",
    "frame.blog:2.desc": "Una tienda sencilla y agradable de recorrer\nLos productos se disponen por categorías en una sola columna, cómoda de recorrer en el móvil",
    "frame.blog:2.recommend": "Tiendas selectas con un catálogo reducido\n※ Para tiendas con muchos productos recomendamos la plantilla Enfoque en navegación.",
    "frame.blog:4.title": "Editorial premium",
    "frame.blog:4.keyword": "Una o pocas categorías",
    "frame.blog:4.desc": "Una tienda que presenta un solo producto como una obra\nGrandes imágenes y una maquetación de revista realzan su valor y detalle, con tonos en blanco y negro y una tipografía sobria",
    "frame.blog:4.recommend": "Mobiliario de diseño premium, marcas de edición limitada",
    "frame.blog:5.title": "Lujo oscuro",
    "frame.blog:5.keyword": "Marca de alta gama y edición limitada",
    "frame.blog:5.desc": "Fondo en tonos oscuros con un ambiente sobrio, elegante y misterioso\nTextos que reflejan el legado de la marca",
    "frame.blog:5.recommend": "Ropa de cama de lujo, artículos del hogar, marcas premium, colecciones limitadas",
    "frame.blog:6.title": "Marca única de confianza",
    "frame.blog:6.keyword": "Pocos artículos · confianza",
    "frame.blog:6.desc": "Diseño ordenado y limpio\nTransmite confianza de forma gradual con puntos de confianza, estadísticas y galería",
    "frame.blog:6.recommend": "Marcas de uno o pocos SKU (agua embotellada, suplementos, línea única de cosmética, bienes de consumo diario, etc.)",
    "frame.blog:7.title": "Minimalismo oriental",
    "frame.blog:7.keyword": "Té · medicina tradicional · naturismo",
    "frame.blog:7.desc": "Tonos beige + palabras clave en caracteres chinos\nTextos sosegados, estética japonesa y oriental",
    "frame.blog:7.recommend": "Té / té medicinal, alimentos tradicionales, cosmética naturista, estilo de vida artesanal",
    "frame.blog:8.title": "Gráfico moderno",
    "frame.blog:8.keyword": "Novedades para público joven",
    "frame.blog:8.desc": "Colores vivos + bloques monocromáticos divididos\nTextos potentes, ambiente gráfico moderno y sofisticado",
    "frame.blog:8.recommend": "Novedades y ediciones limitadas para público joven (belleza indie, zapatillas, cuidado de la salud, accesorios de moda, etc.)",
    "frame.blog:9.title": "Estilo pastel",
    "frame.blog:9.keyword": "Una o pocas categorías",
    "frame.blog:9.desc": "Una tienda de ambiente suave y cálido\nTonos rosas y pastel con aire Polaroid presentan productos y reseñas de forma natural, con un tono cercano y con estilo",
    "frame.blog:9.recommend": "Perfumes, cosmética, accesorios, velas, difusores",
  },
};

export function useSubpageT() {
  const { currentLang } = useLocales();
  const lang = currentLang?.value || 'ko';
  const dict = SUBPAGE_FLAT[lang] || SUBPAGE_FLAT.ko;
  const ko = SUBPAGE_FLAT.ko;
  return (key) => dict[key] ?? ko[key] ?? key;
}

export function useFrameT() {
  const { currentLang } = useLocales();
  const lang = currentLang?.value || 'ko';
  const dict = SUBPAGE_FLAT[lang] || SUBPAGE_FLAT.ko;
  const ko = SUBPAGE_FLAT.ko;
  const g = (k) => dict[k] ?? ko[k];
  return (frameKey) => ({
    title: g(`frame.${frameKey}.title`),
    keyword: g(`frame.${frameKey}.keyword`),
    desc: g(`frame.${frameKey}.desc`),
    recommend: g(`frame.${frameKey}.recommend`),
  });
}
