import { useLocales } from 'src/locales';

// 메인 랜딩 5개국어 카피 (ko 기준, en/ja/cn/es 번역)
export const LANDING_STRINGS = {
  ko: {
    navAbout: '서비스 소개',
    navFrames: '프레임',
    navManual: '매뉴얼',
    navFaq: '자주 묻는 질문',
    ctaCreate: '무료 쇼핑몰 만들기',
    heroLine1: '쇼핑몰 제작비 없이,',
    heroHi: '바로 판매를 시작',
    heroLine2: '하세요.',
    heroSub1: '[[LOGO]]의 무료 쇼핑몰 서비스로,',
    heroSub2: '사업자 누구나 가장 빠르고 간편하게 |나만의 쇼핑몰을 운영할 수 있습니다.',
    heroBtn: '무료 쇼핑몰 만들기',
    heroAddrLabel: '내 쇼핑몰 주소 예시 —',
    heroAddrExample: '내쇼핑몰주소',
    searchTitle: '가맹점·상품 찾기',
    searchPlaceholder: '가맹점명 · 주소 · 상품명으로 검색',
    searchMin: '2글자 이상 입력해 주세요.',
    searchNone: '검색 결과가 없습니다. 가맹점명 · 주소 · 상품명으로 검색해 보세요.',
    searchVisit: '방문하기',
    targetsTitle: '이런 분께 추천드립니다',
    targetsSub: '비용 부담 없이 시작하는 나만의 쇼핑몰! |국내는 물론 해외 고객까지 한 번에 판매하세요.',
    t1Title: '쇼핑몰 제작 비용이 부담되는 사업자',
    t1Desc: '초기 비용 0원,\n유지관리비 부담 없이 간편 운영.',
    t2Title: '해외 고객에게 판매하고 싶은 사업자',
    t2Desc: '해외결제·글로벌결제 지원,\n해외발행카드·위챗페이·알리페이 등.',
    t3Title: 'SNS 중심으로 판매하는 사업자',
    t3Desc: 'SNS에서 상품을 소개하고\nShopGo에서 결제까지 완료.',
    t4Title: '오프라인 매장의 온라인 판매를 시작하려는 사업자',
    t4Desc: '오프라인 매장을 온라인 매출로 연결,\n지역 고객을 전국 고객으로 확대.',
    langsTitle: '다국어 자동 번역',
    langsSub: '상품명과 상세 정보를 자동으로 번역하여, |해외 고객에게도 쉽게 판매할 수 있습니다.',
    langKo: '한국어',
    langEn: '영어',
    langJa: '일본어',
    langCn: '중국어',
    langEs: '스페인어',
    actionsTitle: '지금 바로 시작하기',
    a1Title: '무료 쇼핑몰 프레임 선택',
    a1Desc: '11종 디자인 프레임을 미리 보고 선택하세요.',
    a1Cta: '프레임 보기',
    a2Title: '온라인 쇼핑몰 신청서',
    a2Desc: '사업자 정보 입력 후 무료 쇼핑몰을 신청하세요.',
    a2Cta: '신청하러 가기',
    a3Title: '관리자 매뉴얼',
    a3Desc: '쇼핑몰 운영을 위한 관리자 페이지 가이드.',
    a3Cta: '매뉴얼 받기',
  },
  en: {
    navAbout: 'About',
    navFrames: 'Frames',
    navManual: 'Manual',
    navFaq: 'FAQ',
    ctaCreate: 'Create your free store',
    heroLine1: 'No store-building costs —',
    heroHi: 'start selling right away',
    heroLine2: '.',
    heroSub1: "With [[LOGO]]'s free online store service,",
    heroSub2: 'any business owner can run their own store |in the fastest, easiest way possible.',
    heroBtn: 'Create your free store',
    heroAddrLabel: 'Example of my store address —',
    heroAddrExample: 'your-store',
    searchTitle: 'Find stores & products',
    searchPlaceholder: 'Search by store name, address, or product',
    searchMin: 'Please enter at least 2 characters.',
    searchNone: 'No results found. Try searching by store name, address, or product.',
    searchVisit: 'Visit',
    targetsTitle: 'Perfect for businesses like yours',
    targetsSub: 'Launch your own store with no cost burden—|and sell to customers at home and abroad, all at once.',
    t1Title: 'Businesses worried about store-building costs',
    t1Desc: 'Zero upfront cost—\nrun it easily with no maintenance fees.',
    t2Title: 'Businesses that want to sell to overseas customers',
    t2Desc: 'Overseas & global payments supported—\nforeign cards, WeChat Pay, Alipay, and more.',
    t3Title: 'Businesses selling mainly through social media',
    t3Desc: 'Showcase products on social media\nand complete checkout on ShopGo.',
    t4Title: 'Offline stores starting to sell online',
    t4Desc: 'Turn your offline store into online sales,\nexpanding from local to nationwide customers.',
    langsTitle: 'Automatic multilingual translation',
    langsSub: 'Product names and details are translated automatically, |so you can sell to overseas customers with ease.',
    langKo: 'Korean',
    langEn: 'English',
    langJa: 'Japanese',
    langCn: 'Chinese',
    langEs: 'Spanish',
    actionsTitle: 'Get started right now',
    a1Title: 'Choose your free store frame',
    a1Desc: 'Preview and pick from 11 design frames.',
    a1Cta: 'View frames',
    a2Title: 'Online store application',
    a2Desc: 'Enter your business details and apply for your free store.',
    a2Cta: 'Apply now',
    a3Title: 'Admin manual',
    a3Desc: 'A guide to the admin page for running your store.',
    a3Cta: 'Get the manual',
  },
  ja: {
    navAbout: 'サービス紹介',
    navFrames: 'フレーム',
    navManual: 'マニュアル',
    navFaq: 'よくある質問',
    ctaCreate: '無料ショップを作成',
    heroLine1: 'ショップ制作費0円で、',
    heroHi: '今すぐ販売をスタート',
    heroLine2: 'しましょう。',
    heroSub1: '[[LOGO]]の無料ショップサービスなら、',
    heroSub2: 'どんな事業者でも、もっとも速くかんたんに|自分だけのショップを運営できます。',
    heroBtn: '無料ショップを作成',
    heroAddrLabel: 'あなたのショップアドレス例 —',
    heroAddrExample: 'あなたの店名',
    searchTitle: '加盟店・商品を探す',
    searchPlaceholder: '加盟店名・住所・商品名で検索',
    searchMin: '2文字以上で入力してください。',
    searchNone: '検索結果がありません。加盟店名・住所・商品名で検索してみてください。',
    searchVisit: '訪問する',
    targetsTitle: 'こんな方におすすめです',
    targetsSub: '費用の負担なく始める自分だけのショップ！|国内はもちろん、海外のお客様までまとめて販売しましょう。',
    t1Title: 'ショップ制作費が負担に感じる事業者',
    t1Desc: '初期費用0円、\n維持管理費の負担なくかんたん運営。',
    t2Title: '海外のお客様に販売したい事業者',
    t2Desc: '海外決済・グローバル決済に対応、\n海外発行カード・WeChat Pay・Alipayなど。',
    t3Title: 'SNSを中心に販売する事業者',
    t3Desc: 'SNSで商品を紹介し、\nShopGoで決済まで完了。',
    t4Title: 'オフライン店舗のオンライン販売を始めたい事業者',
    t4Desc: 'オフライン店舗をオンライン売上につなげ、\n地域のお客様を全国のお客様へ拡大。',
    langsTitle: '多言語自動翻訳',
    langsSub: '商品名や詳細情報を自動で翻訳し、|海外のお客様にもかんたんに販売できます。',
    langKo: '韓国語',
    langEn: '英語',
    langJa: '日本語',
    langCn: '中国語',
    langEs: 'スペイン語',
    actionsTitle: '今すぐ始める',
    a1Title: '無料ショップフレームを選択',
    a1Desc: '11種類のデザインフレームをプレビューして選べます。',
    a1Cta: 'フレームを見る',
    a2Title: 'オンラインショップ申込書',
    a2Desc: '事業者情報を入力して、無料ショップをお申し込みください。',
    a2Cta: '申し込みへ進む',
    a3Title: '管理者マニュアル',
    a3Desc: 'ショップ運営のための管理者ページガイド。',
    a3Cta: 'マニュアルを入手',
  },
  cn: {
    navAbout: '服务介绍',
    navFrames: '模板',
    navManual: '使用手册',
    navFaq: '常见问题',
    ctaCreate: '免费创建网店',
    heroLine1: '无需网店搭建费用，',
    heroHi: '立即开启销售',
    heroLine2: '。',
    heroSub1: '借助 [[LOGO]] 的免费网店服务，',
    heroSub2: '每一位商家都能以最快、最简便的方式|运营专属于自己的网店。',
    heroBtn: '免费创建网店',
    heroAddrLabel: '我的网店网址示例 —',
    heroAddrExample: '您的店铺名',
    searchTitle: '查找商户 · 商品',
    searchPlaceholder: '按商户名 · 地址 · 商品名搜索',
    searchMin: '请输入两个字以上。',
    searchNone: '没有搜索结果。请尝试按商户名 · 地址 · 商品名搜索。',
    searchVisit: '前往访问',
    targetsTitle: '推荐给这样的您',
    targetsSub: '零负担开启专属于你的网店！|国内乃至海外客户，一次搞定销售。',
    t1Title: '在意网店搭建成本的商家',
    t1Desc: '零初始成本，\n无维护费负担，轻松运营。',
    t2Title: '希望向海外客户销售的商家',
    t2Desc: '支持海外支付、全球支付，\n境外发行卡、微信支付、支付宝等。',
    t3Title: '以社交媒体为主销售的商家',
    t3Desc: '在社交媒体展示商品，\n在 ShopGo 完成支付。',
    t4Title: '想开启线上销售的线下门店',
    t4Desc: '将线下门店连接到线上销售，\n把本地客户拓展为全国客户。',
    langsTitle: '多语言自动翻译',
    langsSub: '自动翻译商品名称与详细信息，|让您轻松向海外客户销售。',
    langKo: '韩语',
    langEn: '英语',
    langJa: '日语',
    langCn: '中文',
    langEs: '西班牙语',
    actionsTitle: '立即开始',
    a1Title: '选择免费网店模板',
    a1Desc: '预览并挑选 11 款设计模板。',
    a1Cta: '查看模板',
    a2Title: '线上网店申请表',
    a2Desc: '填写商家信息后即可申请免费网店。',
    a2Cta: '前往申请',
    a3Title: '管理员手册',
    a3Desc: '网店运营所需的管理后台指南。',
    a3Cta: '获取手册',
  },
  es: {
    navAbout: 'Servicio',
    navFrames: 'Plantillas',
    navManual: 'Manual',
    navFaq: 'Preguntas frecuentes',
    ctaCreate: 'Crea tu tienda gratis',
    heroLine1: 'Sin costes de creación,',
    heroHi: 'empieza a vender',
    heroLine2: ' hoy mismo.',
    heroSub1: 'Con el servicio de tienda online gratuita de [[LOGO]],',
    heroSub2: 'cualquier negocio puede gestionar su propia tienda |de la forma más rápida y sencilla.',
    heroBtn: 'Crea tu tienda gratis',
    heroAddrLabel: 'Ejemplo de la dirección de mi tienda —',
    heroAddrExample: 'tu-tienda',
    searchTitle: 'Buscar comercios y productos',
    searchPlaceholder: 'Busca por comercio, dirección o producto',
    searchMin: 'Introduce al menos 2 caracteres.',
    searchNone: 'No se encontraron resultados. Prueba a buscar por comercio, dirección o producto.',
    searchVisit: 'Visitar',
    targetsTitle: 'Recomendado para ti si eres así',
    targetsSub: '¡Tu propia tienda sin cargas de coste! |Vende de una sola vez a clientes nacionales y también del extranjero.',
    t1Title: 'Un negocio al que le pesan los costes de crear la tienda',
    t1Desc: 'Coste inicial de 0,\ngestión sencilla sin gastos de mantenimiento.',
    t2Title: 'Un negocio que quiere vender a clientes del extranjero',
    t2Desc: 'Pagos internacionales y globales,\ntarjetas extranjeras, WeChat Pay, Alipay y más.',
    t3Title: 'Un negocio que vende a través de redes sociales',
    t3Desc: 'Muestra tus productos en redes sociales\ny completa el pago en ShopGo.',
    t4Title: 'Una tienda física que empieza a vender online',
    t4Desc: 'Conecta tu tienda física con las ventas online\ny amplía de clientes locales a todo el país.',
    langsTitle: 'Traducción automática multilingüe',
    langsSub: 'Traduce automáticamente los nombres y detalles de tus productos |para vender con facilidad también a clientes del extranjero.',
    langKo: 'Coreano',
    langEn: 'Inglés',
    langJa: 'Japonés',
    langCn: 'Chino',
    langEs: 'Español',
    actionsTitle: 'Empieza ahora mismo',
    a1Title: 'Elige tu plantilla de tienda gratis',
    a1Desc: 'Previsualiza y elige entre 11 plantillas de diseño.',
    a1Cta: 'Ver plantillas',
    a2Title: 'Solicitud de tienda online',
    a2Desc: 'Introduce los datos de tu negocio y solicita tu tienda gratis.',
    a2Cta: 'Ir a la solicitud',
    a3Title: 'Manual del administrador',
    a3Desc: 'Guía del panel de administración para gestionar tu tienda.',
    a3Cta: 'Obtener el manual',
  },
};

// 현재 선택 언어의 랜딩 문자열 반환 (없으면 한국어)
export function useLandingT() {
  const { currentLang } = useLocales();
  const lang = currentLang?.value || 'ko';
  return LANDING_STRINGS[lang] || LANDING_STRINGS.ko;
}

// ----------------------------------------------------------------------
// 서브 페이지(frames / apply / manual) + 프레임 카탈로그 번역 (flat dotted keys)
// 접근: useSubpageT() → st('apply.sec1'), useFrameT() → ft(frameKey) → {title,keyword,desc,recommend}
// ----------------------------------------------------------------------
const SUBPAGE_FLAT = {
  ko: {
    'frames.title': '무료 쇼핑몰 프레임',
    'frames.desc1': '브랜드와 업종에 맞추어 여러 디자인의 쇼핑몰 프레임이 준비되어 있습니다.',
    'frames.desc2': '아래 카드의 미리보기 버튼으로 실제 동작을 확인해 보세요.',
    'frames.recommendLabel': '추천 업종',
    'frames.preview': '미리보기',
    'frames.comingSoon': '준비중',
    'frames.applyBtn': '이 프레임으로 신청',
    'frames.ctaLine1': '마음에 드는 프레임을 선택하셨다면,',
    'frames.ctaLine2': '이제 신청만으로 모든 준비가 완료됩니다.',
    'apply.title': '온라인 쇼핑몰 신청서',
    'apply.desc': '입력하신 내용을 확인 후 담당자가 연락드립니다. 모든 필수 항목 입력 후 약정서에 동의해 주세요.',
    'apply.sec1': '01 · 사업자 정보',
    'apply.sec2': '02 · 대표자 정보',
    'apply.sec3': '03 · 담당자 정보',
    'apply.sec4': '04 · 운영 정보',
    'apply.sec5': '05 · 쇼핑몰 주소 (가맹점명)',
    'apply.sec6': '06 · 프레임 선택',
    'apply.sec7': '07 · 약정서',
    'apply.fBizName': '사업자명',
    'apply.fBizNo': '사업자번호',
    'apply.fMailOrder': '통신판매업신고번호',
    'apply.fCeoName': '대표자명',
    'apply.fCeoPhone': '대표자 연락처',
    'apply.fCeoEmail': '대표자 이메일',
    'apply.fMgrName': '담당자명',
    'apply.fMgrPhone': '담당자 연락처',
    'apply.fMgrEmail': '담당자 이메일',
    'apply.fCsPhone': '고객센터 번호',
    'apply.fReferrer': '영업추천인',
    'apply.fSlug': '사용하실 가맹점명',
    'apply.fFrame': '원하시는 디자인 프레임',
    'apply.phBizNo': '10자리 숫자',
    'apply.phMailOrder': '예: 2024-서울강남-1234',
    'apply.phCsPhone': '1588-0000 등',
    'apply.phReferrer': '추천인이 있으면 입력해 주세요',
    'apply.phSlug': '영문 소문자/숫자/하이픈',
    'apply.framePlaceholder': '프레임 선택',
    'apply.slugExampleWord': '가맹점명',
    'apply.exampleLabel': '예시',
    'apply.frameHintPre': '프레임을 자세히 보려면 ',
    'apply.frameHintLink': '프레임 페이지',
    'apply.frameHintPost': '를 열어 미리보기 후 선택하세요.',
    'apply.cancel': '취소',
    'apply.submit': '신청서 제출',
    'apply.submitting': '접수 중…',
    'apply.alertWarn': '입력값을 확인해 주세요. 누락되거나 형식이 맞지 않는 항목이 있습니다.',
    'apply.agreeLabel': '위 무료 쇼핑몰 제공 약정서 내용을 확인하였으며, 이에 동의합니다. (필수)',
    'apply.agreeError': '약정서 동의가 필요합니다.',
    'apply.vBizName': '사업자명을 입력해 주세요',
    'apply.vBizNo': '사업자번호 10자리를 입력해 주세요',
    'apply.vCeoName': '대표자명을 입력해 주세요',
    'apply.vCeoPhone': '대표자 연락처를 확인해 주세요',
    'apply.vEmail': '이메일 형식을 확인해 주세요',
    'apply.vMgrName': '담당자명을 입력해 주세요',
    'apply.vMgrPhone': '담당자 연락처를 확인해 주세요',
    'apply.vSlug': '영문 소문자/숫자/하이픈 3~30자 (시작·끝은 영숫자)',
    'apply.vFrame': '프레임을 1개 선택해 주세요',
    'apply.vAgreed': '약정서 동의가 필요합니다',
    'apply.tCheckInput': '입력값을 확인해 주세요',
    'apply.tSuccess': '신청이 접수되었습니다',
    'apply.tDupSlug': '이미 사용 중인 URL명입니다',
    'apply.tError': '접수 중 오류가 발생했습니다',
    'apply.tServerError': '서버 오류로 접수에 실패했습니다',
    'manual.title': '관리자 페이지 가이드',
    'manual.desc1': '쇼핑몰 운영에 필요한 모든 메뉴와 기능을 한 권으로 정리한 가이드입니다.',
    'manual.desc2': 'PDF로 다운로드해 언제든 확인할 수 있습니다.',
    'manual.download': '매뉴얼 PDF 다운로드',
    'manual.viewNewTab': '새 탭에서 보기',
    'manual.itemsLabel': '매뉴얼에 포함된 주요 항목',
    'manual.preApply': '아직 신청 전이신가요?',
    'manual.applyLink': '무료 쇼핑몰 신청하기',
    'complete.title': '신청이 접수되었습니다',
    'complete.desc1': '담당자가 검토 후 입력하신 연락처로 연락드리겠습니다.',
    'complete.desc2': '승인이 완료되면 신청하신 가맹점명으로 쇼핑몰이 개설됩니다.',
    'complete.home': '홈으로',
    'complete.manual': '관리자 매뉴얼 받기',
    'manual.h1Title': '대시보드',
    'manual.h1Desc': '주문·매출·회원 현황을 한눈에 확인합니다.',
    'manual.h2Title': '상품 관리',
    'manual.h2Desc': '상품 등록·옵션 설정·재고/품절 관리.',
    'manual.h3Title': '주문 처리',
    'manual.h3Desc': '주문 확인·배송·환불·교환 처리 흐름.',
    'manual.h4Title': '회원 관리',
    'manual.h4Desc': '회원 등급·쿠폰·포인트·CS 응대.',
    'manual.h5Title': '디자인 설정',
    'manual.h5Desc': '프레임 변경·로고·컬러·배너 편집.',
    'manual.h6Title': '운영 설정',
    'manual.h6Desc': '배송비·결제 수단·정책 페이지 관리.',
    'frame.shop:1.title': '탐색 중심형',
    'frame.shop:1.keyword': '다카테고리 종합몰',
    'frame.shop:1.desc': '상단 카테고리 메뉴를 항상 노출해 다수의 상품을 빠르게 탐색. 전체 폭 슬라이드 배너 + 인기상품/품절임박 섹션.',
    'frame.shop:1.recommend': '카테고리·SKU가 많은 종합 쇼핑몰 (가전·잡화·식품 등)',
    'frame.shop:2.title': '브랜드 무드형',
    'frame.shop:2.keyword': '단일/소수 브랜드 매장',
    'frame.shop:2.desc': '큰 메인 배너로 브랜드·시즌 분위기를 강조. 상단 메뉴는 접어두고 비주얼에 집중.',
    'frame.shop:2.recommend': '브랜드 정체성을 강조하는 단일/소수 브랜드 매장 (화장품·패션 등)',
    'frame.shop:4.title': '다카테고리 잡화몰',
    'frame.shop:4.keyword': '패션·잡화 다품목',
    'frame.shop:4.desc': '카테고리별 상품 그리드를 다채롭게 배치. 가방·시계·신발·액세서리 등 종류별 분류 진열.',
    'frame.shop:4.recommend': '카테고리가 많고 SKU가 다양한 잡화몰 (가방·시계·신발·액세서리 등)',
    'frame.blog:1.title': '매거진 에디토리얼',
    'frame.blog:1.keyword': '디자이너 셀렉트샵',
    'frame.blog:1.desc': '"Cover Story" "Editor\'s Pick" 매거진 형식. 단일 상품을 풍성하게 배너로 표현.',
    'frame.blog:1.recommend': '패션, 주얼리, 액세서리, 라이프스타일 큐레이션, 디자이너 브랜드',
    'frame.blog:2.title': '종합 그리드',
    'frame.blog:2.keyword': '종합 큐레이션 몰',
    'frame.blog:2.desc': '다양한 카테고리별 상품 그리드를 빼곡하게 진열. 다품종을 한눈에 보여주는 종합몰 스타일.',
    'frame.blog:2.recommend': '생활/잡화/뷰티/식품 두루 다루는 종합 셀렉트샵, 큐레이션 쇼핑몰',
    'frame.blog:4.title': '럭셔리 미니멀',
    'frame.blog:4.keyword': '단일 프리미엄 상품',
    'frame.blog:4.desc': '단일 상품을 큰 비주얼로 매거진처럼 표현. 흑백 톤, 절제된 타이포그래피.',
    'frame.blog:4.recommend': '단일 프리미엄 상품(가전·디자인 가구·아트 굿즈), 한정 에디션 브랜드',
    'frame.blog:5.title': '다크 럭셔리',
    'frame.blog:5.keyword': '고급·한정판 브랜드',
    'frame.blog:5.desc': '다크 톤 배경으로 절제·고급·신비로운 무드. 브랜드 헤리티지를 담은 문구.',
    'frame.blog:5.recommend': '럭셔리 침구·생활용품, 프리미엄 브랜드, 한정 컬렉션',
    'frame.blog:6.title': '신뢰형 단일 브랜드',
    'frame.blog:6.keyword': '소수 품목 · 신뢰형',
    'frame.blog:6.desc': '정돈된 깔끔한 레이아웃. 신뢰 포인트·통계·갤러리로 믿음을 단계적으로 전달.',
    'frame.blog:6.recommend': '단일/소수 SKU 브랜드 (생수·영양제, 단일 화장품 라인, 일상 소비재 등)',
    'frame.blog:7.title': '동양 미니멀',
    'frame.blog:7.keyword': '차·한방·자연주의',
    'frame.blog:7.desc': '베이지 톤 + 한자 키워드. 차분한 카피, 일본·동양 미감.',
    'frame.blog:7.recommend': '차/한방차, 전통식품, 자연주의 화장품, 수공예 라이프스타일',
    'frame.blog:8.title': '트렌디 그래픽',
    'frame.blog:8.keyword': 'MZ 타깃 신상',
    'frame.blog:8.desc': '비비드 컬러 + 모노크롬 블록 분할. 강한 카피, 트렌디·세련된 그래픽 무드.',
    'frame.blog:8.recommend': 'MZ 타깃 신상품/한정판 (인디 뷰티, 스니커즈, 헬스케어, 트렌디 액세서리 등)',
    'frame.blog:9.title': '파스텔 감성',
    'frame.blog:9.keyword': '여성 라이프스타일',
    'frame.blog:9.desc': '핑크/파스텔 톤. 폴라로이드 모티프, 귀엽고 감성적인 후기. 친근한 여성 타깃 무드.',
    'frame.blog:9.recommend': '향수, 화장품, 액세서리, 캔들·디퓨저 등 여성 라이프스타일',
  },
  en: {
    "frames.title": "Free Online Store Frames",
    "frames.desc1": "A variety of designs are ready to match your brand and industry.",
    "frames.desc2": "Use the preview button on each card below to see it in action.",
    "frames.recommendLabel": "Recommended for",
    "frames.preview": "Preview",
    "frames.comingSoon": "Coming soon",
    "frames.applyBtn": "Apply with this frame",
    "frames.ctaLine1": "Once you've picked a frame you like,",
    "frames.ctaLine2": "just submit your application and you're all set.",
    "apply.title": "Online Store Application",
    "apply.desc": "Our team will contact you after reviewing your submission. Please fill in all required fields and agree to the agreement.",
    "apply.sec1": "01 · Business Info",
    "apply.sec2": "02 · Representative Info",
    "apply.sec3": "03 · Contact Person Info",
    "apply.sec4": "04 · Operations Info",
    "apply.sec5": "05 · Store Address (store name)",
    "apply.sec6": "06 · Frame Selection",
    "apply.sec7": "07 · Agreement",
    "apply.fBizName": "Business name",
    "apply.fBizNo": "Business registration no.",
    "apply.fMailOrder": "Mail-order business report no.",
    "apply.fCeoName": "Representative name",
    "apply.fCeoPhone": "Representative phone",
    "apply.fCeoEmail": "Representative email",
    "apply.fMgrName": "Contact person name",
    "apply.fMgrPhone": "Contact person phone",
    "apply.fMgrEmail": "Contact person email",
    "apply.fCsPhone": "Customer service number",
    "apply.fReferrer": "Sales referrer",
    "apply.fSlug": "Store name to use",
    "apply.fFrame": "Preferred design frame",
    "apply.phBizNo": "10-digit number",
    "apply.phMailOrder": "e.g. 2024-Seoul-Gangnam-1234",
    "apply.phCsPhone": "1588-0000 etc.",
    "apply.phReferrer": "Enter a referrer if you have one",
    "apply.phSlug": "lowercase letters/numbers/hyphens",
    "apply.framePlaceholder": "Select a frame",
    "apply.slugExampleWord": "store-name",
    "apply.exampleLabel": "Example",
    "apply.frameHintPre": "To see frames in detail, open the ",
    "apply.frameHintLink": "frames page",
    "apply.frameHintPost": " to preview them before choosing.",
    "apply.cancel": "Cancel",
    "apply.submit": "Submit application",
    "apply.submitting": "Submitting…",
    "apply.alertWarn": "Please check your entries. Some items are missing or in the wrong format.",
    "apply.agreeLabel": "I have read and agree to the free online store agreement above. (Required)",
    "apply.agreeError": "You must agree to the agreement.",
    "apply.vBizName": "Please enter the business name",
    "apply.vBizNo": "Please enter the 10-digit business registration number",
    "apply.vCeoName": "Please enter the representative name",
    "apply.vCeoPhone": "Please check the representative phone number",
    "apply.vEmail": "Please check the email format",
    "apply.vMgrName": "Please enter the contact person name",
    "apply.vMgrPhone": "Please check the contact person phone number",
    "apply.vSlug": "3–30 lowercase letters/numbers/hyphens (start and end with alphanumeric)",
    "apply.vFrame": "Please select one frame",
    "apply.vAgreed": "You must agree to the agreement",
    "apply.tCheckInput": "Please check your entries",
    "apply.tSuccess": "Your application has been received",
    "apply.tDupSlug": "This URL name is already in use",
    "apply.tError": "An error occurred during submission",
    "apply.tServerError": "Submission failed due to a server error",
    "manual.title": "Admin Page Guide",
    "manual.desc1": "A single guide covering all the menus and features you need to run your store.",
    "manual.desc2": "Download it as a PDF to check anytime.",
    "manual.download": "Download manual PDF",
    "manual.viewNewTab": "Open in new tab",
    "manual.itemsLabel": "Key items in the manual",
    "manual.preApply": "Haven't applied yet?",
    "manual.applyLink": "Apply for a free online store",
    "complete.title": "Your application has been received",
    "complete.desc1": "Our team will review it and contact you at the number you provided.",
    "complete.desc2": "Once approved, your store will open under the store name you requested.",
    "complete.home": "Go home",
    "complete.manual": "Get the admin manual",
    "manual.h1Title": "Dashboard",
    "manual.h1Desc": "See orders, sales, and member status at a glance.",
    "manual.h2Title": "Product Management",
    "manual.h2Desc": "Add products, set options, and manage stock/sold-out status.",
    "manual.h3Title": "Order Processing",
    "manual.h3Desc": "Order confirmation, shipping, refund, and exchange flow.",
    "manual.h4Title": "Member Management",
    "manual.h4Desc": "Member tiers, coupons, points, and customer support.",
    "manual.h5Title": "Design Settings",
    "manual.h5Desc": "Change frames and edit logo, colors, and banners.",
    "manual.h6Title": "Operations Settings",
    "manual.h6Desc": "Manage shipping fees, payment methods, and policy pages.",
    "frame.shop:1.title": "Browse-Focused",
    "frame.shop:1.keyword": "Multi-category general mall",
    "frame.shop:1.desc": "Keeps the top category menu always visible for quickly browsing many products. Full-width slide banner + popular/almost-sold-out sections.",
    "frame.shop:1.recommend": "General stores with many categories and SKUs (electronics, goods, food, etc.)",
    "frame.shop:2.title": "Brand Mood",
    "frame.shop:2.keyword": "Single/few-brand store",
    "frame.shop:2.desc": "Emphasizes brand and seasonal mood with a large main banner. Keeps the top menu collapsed to focus on visuals.",
    "frame.shop:2.recommend": "Single/few-brand stores that emphasize brand identity (cosmetics, fashion, etc.)",
    "frame.shop:4.title": "Multi-category Goods Mall",
    "frame.shop:4.keyword": "Fashion & goods, many items",
    "frame.shop:4.desc": "Arranges product grids by category in a rich layout. Displays items sorted by type such as bags, watches, shoes, and accessories.",
    "frame.shop:4.recommend": "Goods malls with many categories and varied SKUs (bags, watches, shoes, accessories, etc.)",
    "frame.blog:1.title": "Magazine Editorial",
    "frame.blog:1.keyword": "Designer select shop",
    "frame.blog:1.desc": "A \"Cover Story\" and \"Editor's Pick\" magazine format. Presents a single product richly with banners.",
    "frame.blog:1.recommend": "Fashion, jewelry, accessories, lifestyle curation, designer brands",
    "frame.blog:2.title": "General Grid",
    "frame.blog:2.keyword": "General curation mall",
    "frame.blog:2.desc": "Densely displays product grids across various categories. A general-mall style that shows many item types at a glance.",
    "frame.blog:2.recommend": "General select shops and curation malls covering living goods, sundries, beauty, and food",
    "frame.blog:4.title": "Luxury Minimal",
    "frame.blog:4.keyword": "Single premium product",
    "frame.blog:4.desc": "Presents a single product with large visuals, like a magazine. Black-and-white tones and restrained typography.",
    "frame.blog:4.recommend": "Single premium products (electronics, design furniture, art goods), limited-edition brands",
    "frame.blog:5.title": "Dark Luxury",
    "frame.blog:5.keyword": "Premium & limited-edition brand",
    "frame.blog:5.desc": "A dark-toned background for a restrained, upscale, mysterious mood. Copy that conveys brand heritage.",
    "frame.blog:5.recommend": "Luxury bedding and living goods, premium brands, limited collections",
    "frame.blog:6.title": "Trustworthy Single Brand",
    "frame.blog:6.keyword": "Few items · trust-focused",
    "frame.blog:6.desc": "A tidy, clean layout. Builds trust step by step with trust points, statistics, and a gallery.",
    "frame.blog:6.recommend": "Single/few-SKU brands (bottled water, supplements, a single cosmetics line, everyday consumables, etc.)",
    "frame.blog:7.title": "Eastern Minimal",
    "frame.blog:7.keyword": "Tea · herbal · naturalist",
    "frame.blog:7.desc": "Beige tones + Chinese-character keywords. Calm copy with a Japanese/Eastern aesthetic.",
    "frame.blog:7.recommend": "Tea/herbal tea, traditional foods, naturalist cosmetics, handcrafted lifestyle",
    "frame.blog:8.title": "Trendy Graphic",
    "frame.blog:8.keyword": "New arrivals for Gen MZ",
    "frame.blog:8.desc": "Vivid colors + monochrome block divisions. Bold copy with a trendy, refined graphic mood.",
    "frame.blog:8.recommend": "New/limited-edition products targeting Gen MZ (indie beauty, sneakers, healthcare, trendy accessories, etc.)",
    "frame.blog:9.title": "Pastel Sensibility",
    "frame.blog:9.keyword": "Women's lifestyle",
    "frame.blog:9.desc": "Pink/pastel tones. Polaroid motifs and cute, heartfelt reviews. A friendly mood targeting women.",
    "frame.blog:9.recommend": "Perfume, cosmetics, accessories, candles/diffusers, and other women's lifestyle goods"
  },
  ja: {
    "frames.title": "無料ネットショップフレーム",
    "frames.desc1": "ブランドや業種に合わせて、さまざまなデザインをご用意しています。",
    "frames.desc2": "下のカードのプレビューボタンで実際の動作をご確認ください。",
    "frames.recommendLabel": "おすすめ業種",
    "frames.preview": "プレビュー",
    "frames.comingSoon": "準備中",
    "frames.applyBtn": "このフレームで申し込む",
    "frames.ctaLine1": "お気に入りのフレームが決まったら、",
    "frames.ctaLine2": "あとは申し込むだけで、すべての準備が完了します。",
    "apply.title": "オンラインショップ申込書",
    "apply.desc": "ご入力いただいた内容を確認後、担当者からご連絡いたします。すべての必須項目をご入力のうえ、契約書にご同意ください。",
    "apply.sec1": "01 · 事業者情報",
    "apply.sec2": "02 · 代表者情報",
    "apply.sec3": "03 · 担当者情報",
    "apply.sec4": "04 · 運営情報",
    "apply.sec5": "05 · ショップアドレス（店舗名）",
    "apply.sec6": "06 · フレーム選択",
    "apply.sec7": "07 · 契約書",
    "apply.fBizName": "事業者名",
    "apply.fBizNo": "事業者番号",
    "apply.fMailOrder": "通信販売業届出番号",
    "apply.fCeoName": "代表者名",
    "apply.fCeoPhone": "代表者連絡先",
    "apply.fCeoEmail": "代表者メールアドレス",
    "apply.fMgrName": "担当者名",
    "apply.fMgrPhone": "担当者連絡先",
    "apply.fMgrEmail": "担当者メールアドレス",
    "apply.fCsPhone": "カスタマーセンター番号",
    "apply.fReferrer": "営業紹介者",
    "apply.fSlug": "ご利用になる店舗名",
    "apply.fFrame": "ご希望のデザインフレーム",
    "apply.phBizNo": "10桁の数字",
    "apply.phMailOrder": "例: 2024-東京渋谷-1234",
    "apply.phCsPhone": "1588-0000 など",
    "apply.phReferrer": "紹介者がいる場合はご入力ください",
    "apply.phSlug": "半角英小文字／数字／ハイフン",
    "apply.framePlaceholder": "フレーム選択",
    "apply.slugExampleWord": "店舗名",
    "apply.exampleLabel": "例",
    "apply.frameHintPre": "フレームを詳しく見るには",
    "apply.frameHintLink": "フレームページ",
    "apply.frameHintPost": "を開き、プレビューしてから選択してください。",
    "apply.cancel": "キャンセル",
    "apply.submit": "申込書を送信",
    "apply.submitting": "受付中…",
    "apply.alertWarn": "入力内容をご確認ください。未入力または形式が正しくない項目があります。",
    "apply.agreeLabel": "上記の無料ネットショップ提供契約書の内容を確認し、これに同意します。（必須）",
    "apply.agreeError": "契約書への同意が必要です。",
    "apply.vBizName": "事業者名をご入力ください",
    "apply.vBizNo": "事業者番号10桁をご入力ください",
    "apply.vCeoName": "代表者名をご入力ください",
    "apply.vCeoPhone": "代表者連絡先をご確認ください",
    "apply.vEmail": "メールアドレスの形式をご確認ください",
    "apply.vMgrName": "担当者名をご入力ください",
    "apply.vMgrPhone": "担当者連絡先をご確認ください",
    "apply.vSlug": "半角英小文字／数字／ハイフン3～30文字（先頭・末尾は英数字）",
    "apply.vFrame": "フレームを1つ選択してください",
    "apply.vAgreed": "契約書への同意が必要です",
    "apply.tCheckInput": "入力内容をご確認ください",
    "apply.tSuccess": "お申し込みを受け付けました",
    "apply.tDupSlug": "すでに使用されているURL名です",
    "apply.tError": "受付中にエラーが発生しました",
    "apply.tServerError": "サーバーエラーにより受付に失敗しました",
    "manual.title": "管理者ページガイド",
    "manual.desc1": "ショップ運営に必要なすべてのメニューと機能を一冊にまとめたガイドです。",
    "manual.desc2": "PDFでダウンロードして、いつでもご確認いただけます。",
    "manual.download": "マニュアルPDFダウンロード",
    "manual.viewNewTab": "新しいタブで見る",
    "manual.itemsLabel": "マニュアルに含まれる主な項目",
    "manual.preApply": "まだお申し込み前ですか？",
    "manual.applyLink": "無料ネットショップを申し込む",
    "complete.title": "お申し込みを受け付けました",
    "complete.desc1": "担当者が確認のうえ、ご入力の連絡先へご連絡いたします。",
    "complete.desc2": "承認が完了すると、お申し込みの店舗名でショップが開設されます。",
    "complete.home": "ホームへ",
    "complete.manual": "管理者マニュアルを入手",
    "manual.h1Title": "ダッシュボード",
    "manual.h1Desc": "注文・売上・会員状況をひと目で確認できます。",
    "manual.h2Title": "商品管理",
    "manual.h2Desc": "商品登録・オプション設定・在庫／品切れ管理。",
    "manual.h3Title": "注文処理",
    "manual.h3Desc": "注文確認・配送・返金・交換の処理フロー。",
    "manual.h4Title": "会員管理",
    "manual.h4Desc": "会員ランク・クーポン・ポイント・CS対応。",
    "manual.h5Title": "デザイン設定",
    "manual.h5Desc": "フレーム変更・ロゴ・カラー・バナー編集。",
    "manual.h6Title": "運営設定",
    "manual.h6Desc": "送料・決済手段・ポリシーページ管理。",
    "frame.shop:1.title": "探索重視型",
    "frame.shop:1.keyword": "多カテゴリー総合モール",
    "frame.shop:1.desc": "上部カテゴリーメニューを常に表示し、多数の商品をすばやく探索。全幅スライドバナー＋人気商品／品切れ間近セクション。",
    "frame.shop:1.recommend": "カテゴリー・SKUが多い総合ショップ（家電・雑貨・食品など）",
    "frame.shop:2.title": "ブランドムード型",
    "frame.shop:2.keyword": "単一／少数ブランド店舗",
    "frame.shop:2.desc": "大きなメインバナーでブランドやシーズンの雰囲気を強調。上部メニューは折りたたみ、ビジュアルに集中。",
    "frame.shop:2.recommend": "ブランドアイデンティティを強調する単一／少数ブランド店舗（化粧品・ファッションなど）",
    "frame.shop:4.title": "多カテゴリー雑貨モール",
    "frame.shop:4.keyword": "ファッション・雑貨の多品目",
    "frame.shop:4.desc": "カテゴリーごとの商品グリッドを多彩に配置。バッグ・時計・靴・アクセサリーなど種類別に分類して陳列。",
    "frame.shop:4.recommend": "カテゴリーが多くSKUが豊富な雑貨モール（バッグ・時計・靴・アクセサリーなど）",
    "frame.blog:1.title": "マガジンエディトリアル",
    "frame.blog:1.keyword": "デザイナーセレクトショップ",
    "frame.blog:1.desc": "「Cover Story」「Editor's Pick」マガジン形式。単一商品を豊かにバナーで表現。",
    "frame.blog:1.recommend": "ファッション、ジュエリー、アクセサリー、ライフスタイルキュレーション、デザイナーブランド",
    "frame.blog:2.title": "総合グリッド",
    "frame.blog:2.keyword": "総合キュレーションモール",
    "frame.blog:2.desc": "さまざまなカテゴリー別の商品グリッドをぎっしり陳列。多品種をひと目で見せる総合モールスタイル。",
    "frame.blog:2.recommend": "生活／雑貨／ビューティー／食品を幅広く扱う総合セレクトショップ、キュレーションショップ",
    "frame.blog:4.title": "ラグジュアリーミニマル",
    "frame.blog:4.keyword": "単一プレミアム商品",
    "frame.blog:4.desc": "単一商品を大きなビジュアルでマガジンのように表現。モノトーン、抑えの効いたタイポグラフィ。",
    "frame.blog:4.recommend": "単一プレミアム商品（家電・デザイン家具・アートグッズ）、限定エディションブランド",
    "frame.blog:5.title": "ダークラグジュアリー",
    "frame.blog:5.keyword": "高級・限定版ブランド",
    "frame.blog:5.desc": "ダークトーンの背景で抑制・高級・神秘的なムード。ブランドヘリテージを込めたコピー。",
    "frame.blog:5.recommend": "ラグジュアリー寝具・生活用品、プレミアムブランド、限定コレクション",
    "frame.blog:6.title": "信頼型単一ブランド",
    "frame.blog:6.keyword": "少数品目・信頼型",
    "frame.blog:6.desc": "整った清潔なレイアウト。信頼ポイント・統計・ギャラリーで信頼を段階的に伝達。",
    "frame.blog:6.recommend": "単一／少数SKUブランド（ミネラルウォーター・サプリメント、単一化粧品ライン、日用消費財など）",
    "frame.blog:7.title": "東洋ミニマル",
    "frame.blog:7.keyword": "茶・漢方・ナチュラル志向",
    "frame.blog:7.desc": "ベージュトーン＋漢字キーワード。落ち着いたコピー、日本・東洋の美意識。",
    "frame.blog:7.recommend": "茶／漢方茶、伝統食品、ナチュラル志向の化粧品、手工芸ライフスタイル",
    "frame.blog:8.title": "トレンディグラフィック",
    "frame.blog:8.keyword": "Z世代ターゲット新商品",
    "frame.blog:8.desc": "ビビッドカラー＋モノクロームのブロック分割。強いコピー、トレンディで洗練されたグラフィックムード。",
    "frame.blog:8.recommend": "Z世代ターゲットの新商品／限定版（インディーズビューティー、スニーカー、ヘルスケア、トレンディなアクセサリーなど）",
    "frame.blog:9.title": "パステル感性",
    "frame.blog:9.keyword": "女性向けライフスタイル",
    "frame.blog:9.desc": "ピンク／パステルトーン。ポラロイドモチーフ、かわいく情緒的なレビュー。親しみやすい女性ターゲットのムード。",
    "frame.blog:9.recommend": "香水、化粧品、アクセサリー、キャンドル・ディフューザーなど女性向けライフスタイル"
  },
  cn: {
    "frames.title": "免费商城框架",
    "frames.desc1": "我们已为各类品牌和行业准备了多种设计方案。",
    "frames.desc2": "请点击下方卡片的预览按钮，查看实际效果。",
    "frames.recommendLabel": "推荐行业",
    "frames.preview": "预览",
    "frames.comingSoon": "敬请期待",
    "frames.applyBtn": "使用此框架申请",
    "frames.ctaLine1": "如果您已选好心仪的框架，",
    "frames.ctaLine2": "现在只需提交申请，一切准备即可就绪。",
    "apply.title": "网上商城申请表",
    "apply.desc": "确认您填写的内容后，专员将与您联系。请填写所有必填项并同意约定书。",
    "apply.sec1": "01 · 工商信息",
    "apply.sec2": "02 · 法人代表信息",
    "apply.sec3": "03 · 负责人信息",
    "apply.sec4": "04 · 运营信息",
    "apply.sec5": "05 · 商城地址（店铺名）",
    "apply.sec6": "06 · 框架选择",
    "apply.sec7": "07 · 约定书",
    "apply.fBizName": "企业名称",
    "apply.fBizNo": "营业执照号",
    "apply.fMailOrder": "网络销售业申报号",
    "apply.fCeoName": "法人代表姓名",
    "apply.fCeoPhone": "法人代表联系电话",
    "apply.fCeoEmail": "法人代表邮箱",
    "apply.fMgrName": "负责人姓名",
    "apply.fMgrPhone": "负责人联系电话",
    "apply.fMgrEmail": "负责人邮箱",
    "apply.fCsPhone": "客服中心电话",
    "apply.fReferrer": "业务推荐人",
    "apply.fSlug": "要使用的店铺名",
    "apply.fFrame": "您希望的设计框架",
    "apply.phBizNo": "10 位数字",
    "apply.phMailOrder": "例：2024-首尔江南-1234",
    "apply.phCsPhone": "1588-0000 等",
    "apply.phReferrer": "如有推荐人请填写",
    "apply.phSlug": "小写英文字母／数字／连字符",
    "apply.framePlaceholder": "选择框架",
    "apply.slugExampleWord": "店铺名",
    "apply.exampleLabel": "示例",
    "apply.frameHintPre": "如需查看框架详情，请打开",
    "apply.frameHintLink": "框架页面",
    "apply.frameHintPost": "预览后进行选择。",
    "apply.cancel": "取消",
    "apply.submit": "提交申请表",
    "apply.submitting": "受理中…",
    "apply.alertWarn": "请检查您的输入内容。存在遗漏或格式不正确的项目。",
    "apply.agreeLabel": "我已阅读上述免费商城提供约定书的内容，并表示同意。（必填）",
    "apply.agreeError": "需要同意约定书。",
    "apply.vBizName": "请输入企业名称",
    "apply.vBizNo": "请输入 10 位营业执照号",
    "apply.vCeoName": "请输入法人代表姓名",
    "apply.vCeoPhone": "请核对法人代表联系电话",
    "apply.vEmail": "请核对邮箱格式",
    "apply.vMgrName": "请输入负责人姓名",
    "apply.vMgrPhone": "请核对负责人联系电话",
    "apply.vSlug": "小写英文字母／数字／连字符 3～30 位（首尾须为英文或数字）",
    "apply.vFrame": "请选择 1 个框架",
    "apply.vAgreed": "需要同意约定书",
    "apply.tCheckInput": "请检查输入内容",
    "apply.tSuccess": "申请已受理",
    "apply.tDupSlug": "该 URL 名称已被占用",
    "apply.tError": "受理过程中发生错误",
    "apply.tServerError": "因服务器错误受理失败",
    "manual.title": "管理员页面指南",
    "manual.desc1": "这是一本将商城运营所需的所有菜单与功能汇整于一册的指南。",
    "manual.desc2": "可下载为 PDF，随时查阅。",
    "manual.download": "下载手册 PDF",
    "manual.viewNewTab": "在新标签页中查看",
    "manual.itemsLabel": "手册包含的主要内容",
    "manual.preApply": "还未申请吗？",
    "manual.applyLink": "申请免费商城",
    "complete.title": "申请已受理",
    "complete.desc1": "专员将审核后通过您填写的联系方式与您联系。",
    "complete.desc2": "审核通过后，将以您申请的店铺名开设网店。",
    "complete.home": "返回首页",
    "complete.manual": "获取管理员手册",
    "manual.h1Title": "仪表盘",
    "manual.h1Desc": "一目了然地查看订单、销售额与会员情况。",
    "manual.h2Title": "商品管理",
    "manual.h2Desc": "商品登记、选项设置、库存／缺货管理。",
    "manual.h3Title": "订单处理",
    "manual.h3Desc": "订单确认、配送、退款、换货处理流程。",
    "manual.h4Title": "会员管理",
    "manual.h4Desc": "会员等级、优惠券、积分、客服应对。",
    "manual.h5Title": "设计设置",
    "manual.h5Desc": "框架更换、Logo、配色、横幅编辑。",
    "manual.h6Title": "运营设置",
    "manual.h6Desc": "运费、支付方式、政策页面管理。",
    "frame.shop:1.title": "探索导向型",
    "frame.shop:1.keyword": "多品类综合商城",
    "frame.shop:1.desc": "顶部品类菜单始终展示，快速浏览海量商品。全宽轮播横幅 + 人气商品／即将售罄板块。",
    "frame.shop:1.recommend": "品类与 SKU 众多的综合商城（家电、杂货、食品等）",
    "frame.shop:2.title": "品牌氛围型",
    "frame.shop:2.keyword": "单一／少数品牌门店",
    "frame.shop:2.desc": "以大幅主横幅强调品牌与季节氛围。收起顶部菜单，专注于视觉呈现。",
    "frame.shop:2.recommend": "强调品牌个性的单一／少数品牌门店（化妆品、时尚等）",
    "frame.shop:4.title": "多品类杂货商城",
    "frame.shop:4.keyword": "时尚·杂货多品项",
    "frame.shop:4.desc": "按品类丰富排布商品网格。按包袋、手表、鞋履、饰品等种类分类陈列。",
    "frame.shop:4.recommend": "品类繁多、SKU 多样的杂货商城（包袋、手表、鞋履、饰品等）",
    "frame.blog:1.title": "杂志编辑型",
    "frame.blog:1.keyword": "设计师精选店",
    "frame.blog:1.desc": "\"Cover Story\"\"Editor's Pick\"杂志形式。以丰富的横幅呈现单一商品。",
    "frame.blog:1.recommend": "时尚、珠宝、饰品、生活方式策展、设计师品牌",
    "frame.blog:2.title": "综合网格型",
    "frame.blog:2.keyword": "综合策展商城",
    "frame.blog:2.desc": "按各类品类密集陈列商品网格。一目了然展示多品种的综合商城风格。",
    "frame.blog:2.recommend": "兼顾生活、杂货、美妆、食品的综合精选店、策展商城",
    "frame.blog:4.title": "奢华极简",
    "frame.blog:4.keyword": "单一高端商品",
    "frame.blog:4.desc": "以大幅视觉如杂志般呈现单一商品。黑白色调，简约克制的字体。",
    "frame.blog:4.recommend": "单一高端商品（家电、设计家具、艺术周边）、限量版品牌",
    "frame.blog:5.title": "暗黑奢华",
    "frame.blog:5.keyword": "高端·限量版品牌",
    "frame.blog:5.desc": "暗色调背景营造克制、高级、神秘的氛围。融入品牌传承的文案。",
    "frame.blog:5.recommend": "奢华寝具·生活用品、高端品牌、限量系列",
    "frame.blog:6.title": "信赖型单一品牌",
    "frame.blog:6.keyword": "少数品项 · 信赖型",
    "frame.blog:6.desc": "整洁规整的布局。通过信赖要点、数据、图库逐步传递信任感。",
    "frame.blog:6.recommend": "单一／少数 SKU 品牌（矿泉水、营养品、单一化妆品线、日常消费品等）",
    "frame.blog:7.title": "东方极简",
    "frame.blog:7.keyword": "茶·韩方·自然主义",
    "frame.blog:7.desc": "米色调 + 汉字关键词。沉稳的文案，日式·东方美感。",
    "frame.blog:7.recommend": "茶／韩方茶、传统食品、自然主义化妆品、手工艺生活方式",
    "frame.blog:8.title": "潮流图形",
    "frame.blog:8.keyword": "面向 Z 世代新品",
    "frame.blog:8.desc": "鲜艳配色 + 单色块面分割。强烈文案，潮流·精致的图形氛围。",
    "frame.blog:8.recommend": "面向 Z 世代的新品／限量版（独立美妆、球鞋、健康护理、潮流饰品等）",
    "frame.blog:9.title": "柔和感性",
    "frame.blog:9.keyword": "女性生活方式",
    "frame.blog:9.desc": "粉色／柔和色调。宝丽来元素，可爱感性的评价。亲切的女性受众氛围。",
    "frame.blog:9.recommend": "香水、化妆品、饰品、香薰蜡烛·扩香器等女性生活方式"
  },
  es: {
    "frames.title": "Plantilla de tienda online gratuita",
    "frames.desc1": "Tenemos varios diseños preparados según la marca y el sector.",
    "frames.desc2": "Comprueba el funcionamiento real con el botón de vista previa de las tarjetas de abajo.",
    "frames.recommendLabel": "Sector recomendado",
    "frames.preview": "Vista previa",
    "frames.comingSoon": "Próximamente",
    "frames.applyBtn": "Solicitar con esta plantilla",
    "frames.ctaLine1": "Si has elegido la plantilla que te gusta,",
    "frames.ctaLine2": "ahora solo con la solicitud todo queda listo.",
    "apply.title": "Formulario de solicitud de tienda online",
    "apply.desc": "Tras revisar los datos introducidos, un responsable se pondrá en contacto contigo. Rellena todos los campos obligatorios y acepta el contrato.",
    "apply.sec1": "01 · Datos de la empresa",
    "apply.sec2": "02 · Datos del representante",
    "apply.sec3": "03 · Datos del responsable",
    "apply.sec4": "04 · Datos de operación",
    "apply.sec5": "05 · Dirección de la tienda (nombre de tienda)",
    "apply.sec6": "06 · Selección de plantilla",
    "apply.sec7": "07 · Contrato",
    "apply.fBizName": "Nombre de la empresa",
    "apply.fBizNo": "Número de empresa",
    "apply.fMailOrder": "Nº de registro de venta a distancia",
    "apply.fCeoName": "Nombre del representante",
    "apply.fCeoPhone": "Teléfono del representante",
    "apply.fCeoEmail": "Correo del representante",
    "apply.fMgrName": "Nombre del responsable",
    "apply.fMgrPhone": "Teléfono del responsable",
    "apply.fMgrEmail": "Correo del responsable",
    "apply.fCsPhone": "Número de atención al cliente",
    "apply.fReferrer": "Recomendador comercial",
    "apply.fSlug": "Nombre de tienda que usarás",
    "apply.fFrame": "Plantilla de diseño deseada",
    "apply.phBizNo": "10 dígitos numéricos",
    "apply.phMailOrder": "e.j.: 2024-Madrid-1234",
    "apply.phCsPhone": "1588-0000 etc.",
    "apply.phReferrer": "Si tienes un recomendador, introdúcelo",
    "apply.phSlug": "Minúsculas/números/guiones",
    "apply.framePlaceholder": "Seleccionar plantilla",
    "apply.slugExampleWord": "nombre-tienda",
    "apply.exampleLabel": "Ejemplo",
    "apply.frameHintPre": "Para ver las plantillas en detalle, abre la ",
    "apply.frameHintLink": "página de plantillas",
    "apply.frameHintPost": " y selecciona tras la vista previa.",
    "apply.cancel": "Cancelar",
    "apply.submit": "Enviar solicitud",
    "apply.submitting": "Procesando…",
    "apply.alertWarn": "Revisa los datos introducidos. Hay campos que faltan o con un formato incorrecto.",
    "apply.agreeLabel": "He leído el contenido del contrato de suministro de tienda online gratuita anterior y lo acepto. (obligatorio)",
    "apply.agreeError": "Es necesario aceptar el contrato.",
    "apply.vBizName": "Introduce el nombre de la empresa",
    "apply.vBizNo": "Introduce los 10 dígitos del número de empresa",
    "apply.vCeoName": "Introduce el nombre del representante",
    "apply.vCeoPhone": "Comprueba el teléfono del representante",
    "apply.vEmail": "Comprueba el formato del correo",
    "apply.vMgrName": "Introduce el nombre del responsable",
    "apply.vMgrPhone": "Comprueba el teléfono del responsable",
    "apply.vSlug": "Minúsculas/números/guiones, 3~30 caracteres (inicio y fin alfanuméricos)",
    "apply.vFrame": "Selecciona una plantilla",
    "apply.vAgreed": "Es necesario aceptar el contrato",
    "apply.tCheckInput": "Revisa los datos introducidos",
    "apply.tSuccess": "Tu solicitud ha sido recibida",
    "apply.tDupSlug": "Este nombre de URL ya está en uso",
    "apply.tError": "Se ha producido un error durante el registro",
    "apply.tServerError": "El registro falló por un error del servidor",
    "manual.title": "Guía del panel de administración",
    "manual.desc1": "Es una guía que reúne en un solo lugar todos los menús y funciones necesarios para gestionar la tienda.",
    "manual.desc2": "Puedes descargarla en PDF y consultarla en cualquier momento.",
    "manual.download": "Descargar manual en PDF",
    "manual.viewNewTab": "Ver en pestaña nueva",
    "manual.itemsLabel": "Elementos principales incluidos en el manual",
    "manual.preApply": "¿Aún no has solicitado?",
    "manual.applyLink": "Solicitar tienda online gratuita",
    "complete.title": "Tu solicitud ha sido recibida",
    "complete.desc1": "Nuestro equipo la revisará y te contactará al número que indicaste.",
    "complete.desc2": "Una vez aprobada, tu tienda se abrirá con el nombre de tienda que solicitaste.",
    "complete.home": "Ir al inicio",
    "complete.manual": "Obtener el manual del administrador",
    "manual.h1Title": "Panel de control",
    "manual.h1Desc": "Consulta de un vistazo el estado de pedidos, ventas y socios.",
    "manual.h2Title": "Gestión de productos",
    "manual.h2Desc": "Registro de productos, configuración de opciones y gestión de stock/agotados.",
    "manual.h3Title": "Procesamiento de pedidos",
    "manual.h3Desc": "Flujo de confirmación de pedidos, envío, reembolso y cambio.",
    "manual.h4Title": "Gestión de socios",
    "manual.h4Desc": "Niveles de socios, cupones, puntos y atención al cliente.",
    "manual.h5Title": "Configuración de diseño",
    "manual.h5Desc": "Cambio de plantilla, logotipo, colores y edición de banners.",
    "manual.h6Title": "Configuración de operación",
    "manual.h6Desc": "Gestión de gastos de envío, métodos de pago y páginas de políticas.",
    "frame.shop:1.title": "Enfoque en navegación",
    "frame.shop:1.keyword": "Centro comercial multicategoría",
    "frame.shop:1.desc": "Muestra siempre el menú de categorías superior para explorar rápidamente numerosos productos. Banner deslizante a todo ancho + secciones de productos populares/casi agotados.",
    "frame.shop:1.recommend": "Tiendas integrales con muchas categorías y SKU (electrodomésticos, artículos varios, alimentación, etc.)",
    "frame.shop:2.title": "Ambiente de marca",
    "frame.shop:2.keyword": "Tienda de una o pocas marcas",
    "frame.shop:2.desc": "Destaca el ambiente de la marca y la temporada con un gran banner principal. El menú superior queda plegado para centrarse en lo visual.",
    "frame.shop:2.recommend": "Tiendas de una o pocas marcas que enfatizan la identidad de marca (cosmética, moda, etc.)",
    "frame.shop:4.title": "Tienda de artículos multicategoría",
    "frame.shop:4.keyword": "Moda y artículos variados",
    "frame.shop:4.desc": "Distribuye de forma variada la cuadrícula de productos por categoría. Exhibición clasificada por tipos: bolsos, relojes, zapatos, accesorios, etc.",
    "frame.shop:4.recommend": "Tiendas de artículos varios con muchas categorías y SKU diversos (bolsos, relojes, zapatos, accesorios, etc.)",
    "frame.blog:1.title": "Editorial de revista",
    "frame.blog:1.keyword": "Select shop de diseñador",
    "frame.blog:1.desc": "Formato de revista con \"Cover Story\" y \"Editor's Pick\". Presenta un solo producto de forma rica mediante banners.",
    "frame.blog:1.recommend": "Moda, joyería, accesorios, curaduría de estilo de vida, marcas de diseñador",
    "frame.blog:2.title": "Cuadrícula integral",
    "frame.blog:2.keyword": "Tienda de curaduría integral",
    "frame.blog:2.desc": "Exhibe densamente cuadrículas de productos de diversas categorías. Estilo de tienda integral que muestra muchos productos de un vistazo.",
    "frame.blog:2.recommend": "Select shop integral y tienda de curaduría que abarca hogar, artículos varios, belleza y alimentación",
    "frame.blog:4.title": "Lujo minimalista",
    "frame.blog:4.keyword": "Producto premium único",
    "frame.blog:4.desc": "Presenta un solo producto con gran impacto visual, como una revista. Tonos en blanco y negro, tipografía sobria.",
    "frame.blog:4.recommend": "Producto premium único (electrodomésticos, muebles de diseño, artículos de arte), marcas de edición limitada",
    "frame.blog:5.title": "Lujo oscuro",
    "frame.blog:5.keyword": "Marca de alta gama y edición limitada",
    "frame.blog:5.desc": "Fondo en tonos oscuros con un ambiente sobrio, elegante y misterioso. Textos que reflejan el legado de la marca.",
    "frame.blog:5.recommend": "Ropa de cama de lujo, artículos del hogar, marcas premium, colecciones limitadas",
    "frame.blog:6.title": "Marca única de confianza",
    "frame.blog:6.keyword": "Pocos artículos · confianza",
    "frame.blog:6.desc": "Diseño ordenado y limpio. Transmite confianza de forma gradual con puntos de confianza, estadísticas y galería.",
    "frame.blog:6.recommend": "Marcas de uno o pocos SKU (agua embotellada, suplementos, línea única de cosmética, bienes de consumo diario, etc.)",
    "frame.blog:7.title": "Minimalismo oriental",
    "frame.blog:7.keyword": "Té · medicina tradicional · naturismo",
    "frame.blog:7.desc": "Tonos beige + palabras clave en caracteres chinos. Textos sosegados, estética japonesa y oriental.",
    "frame.blog:7.recommend": "Té / té medicinal, alimentos tradicionales, cosmética naturista, estilo de vida artesanal",
    "frame.blog:8.title": "Gráfico moderno",
    "frame.blog:8.keyword": "Novedades para público joven",
    "frame.blog:8.desc": "Colores vivos + bloques monocromáticos divididos. Textos potentes, ambiente gráfico moderno y sofisticado.",
    "frame.blog:8.recommend": "Novedades y ediciones limitadas para público joven (belleza indie, zapatillas, cuidado de la salud, accesorios de moda, etc.)",
    "frame.blog:9.title": "Estética pastel",
    "frame.blog:9.keyword": "Estilo de vida femenino",
    "frame.blog:9.desc": "Tonos rosa/pastel. Motivo polaroid, reseñas tiernas y emotivas. Ambiente cercano orientado al público femenino.",
    "frame.blog:9.recommend": "Perfumes, cosmética, accesorios, velas y difusores y demás estilo de vida femenino"
  },
};

export function useSubpageT() {
  const { currentLang } = useLocales();
  const lang = currentLang?.value || 'ko';
  const dict = SUBPAGE_FLAT[lang] || SUBPAGE_FLAT.ko;
  const ko = SUBPAGE_FLAT.ko;
  return (key) => dict[key] ?? ko[key] ?? key;
}

export function useFrameT() {
  const { currentLang } = useLocales();
  const lang = currentLang?.value || 'ko';
  const dict = SUBPAGE_FLAT[lang] || SUBPAGE_FLAT.ko;
  const ko = SUBPAGE_FLAT.ko;
  const g = (k) => dict[k] ?? ko[k];
  return (frameKey) => ({
    title: g(`frame.${frameKey}.title`),
    keyword: g(`frame.${frameKey}.keyword`),
    desc: g(`frame.${frameKey}.desc`),
    recommend: g(`frame.${frameKey}.recommend`),
  });
}
